### PR TITLE
Threshold detection agent

### PR DESCRIPTION
**Pull request by zbeech**
Added two simple agents:

1. SysMonAgent: monitors utilization of system resources (CPU, memory, disk)
2. ThresholdDetectionAgent: listens to topics and publish alerts when thresholds are passed

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/482)

### CODE REVIEW

**Comment by craig8** [comment]
Reviewed 3 of 8 files at r1, 1 of 3 files at r2.
Review status: 4 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[services/core/SysMonAgent/setup.py, line 1 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZOaVSni8tc3DHLCo4:-KGZOaVSni8tc3DHLCo5:-484851988) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/setup.py#L1)):*
Missing header

---

*[services/core/SysMonAgent/sysmon/agent.py, line 4 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGYp1-OudbBRgxYo77H:-KGYp1-PvCFyXov98way:-860100289) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/sysmon/agent.py#L4)):*
Please update copyright here.

---

*[services/core/SysMonAgent/sysmon/agent.py, line 74 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGYpAGcsV-IhTqoeFuC:-KGYpAGcsV-IhTqoeFuD:-672781206) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/sysmon/agent.py#L74)):*
Remove the wrapper code.  We want to be able to get the api through readthedocs.  There is an example in the actuator agent.

---

*[services/core/SysMonAgent/sysmon/agent.py, line 87 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGYqDftvI3JOYi_aQwE:-KGYqDfugmaRgvh9Eq_E:680336798) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/sysmon/agent.py#L87)):*
Please add an rpc method so that this endpoint can be modified.  I need to be able specify a uuid of the platform (relative to volttron central).  Also, is this agent meant to be used with/in conjuncture with the monitoriing that the platform instance is doing

---

*[services/core/ThresholdDetectionAgent/setup.py, line 1 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZOgdeOJDJB_e2AbVS:-KGZOgdf5Necy4sk4p3m:-484851988) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/setup.py#L1)):*
Missing header

---

*[services/core/ThresholdDetectionAgent/thresholddetection/agent.py, line 4 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZOqwOD3j4wui7A9xl:-KGZOqwOD3j4wui7A9xm:-1645325246) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/thresholddetection/agent.py#L4)):*
Copyright

---

*[services/core/ThresholdDetectionAgent/thresholddetection/agent.py, line 73 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZOvEezon12qOaSBVk:-KGZOvEfRV5NgnPDLPL2:667414789) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/thresholddetection/agent.py#L73)):*
Please remove wrapper so sphinx can grab your api

---

*[services/core/ThresholdDetectionAgent/thresholddetection/agent.py, line 89 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZP4UUu-BE4K4Sgg-q:-KGZP4UV1h9TfXab_HXo:1472355894) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/thresholddetection/agent.py#L89)):*
Add specific example of configuration to the document here.  This will be included in sphinx

---

*[services/core/ThresholdDetectionAgent/thresholddetection/agent.py, line 132 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZPOkN9yI-5Km3NuHy:-KGZPOkN9yI-5Km3NuHz:-583001721) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/thresholddetection/agent.py#L132)):*
The subsystem is now implemented....

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/482)*

**Comment by zbeech** [comment]
Review status: 3 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[services/core/SysMonAgent/setup.py, line 1 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZOaVSni8tc3DHLCo4:-KGme3QNAjRLNKXGUxpO:-499146009) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/setup.py#L1)):*
Done.

---

*[services/core/SysMonAgent/sysmon/agent.py, line 4 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGYp1-OudbBRgxYo77H:-KGme432S726Bw12US1d:-499146009) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/sysmon/agent.py#L4)):*
Done.

---

*[services/core/SysMonAgent/sysmon/agent.py, line 74 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGYpAGcsV-IhTqoeFuC:-KGme4Tk_a_mlCnzmXTf:-499146009) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/sysmon/agent.py#L74)):*
Done.

---

*[services/core/SysMonAgent/sysmon/agent.py, line 87 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGYqDftvI3JOYi_aQwE:-KGmdFM0rOpD1ZCgB6QO:-1850358951) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/sysmon/agent.py#L87)):*
I added an RPC method to change the endpoint. I'll work with you to figure out how we want the platform agent to utilize SysMonAgent.

---

*[services/core/ThresholdDetectionAgent/setup.py, line 1 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZOgdeOJDJB_e2AbVS:-KGme5WllwyTzEXCH7Eb:-499146009) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/setup.py#L1)):*
Done.

---

*[services/core/ThresholdDetectionAgent/thresholddetection/agent.py, line 4 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZOqwOD3j4wui7A9xl:-KGme5zhGbv_u6Was66m:-499146009) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/thresholddetection/agent.py#L4)):*
Done.

---

*[services/core/ThresholdDetectionAgent/thresholddetection/agent.py, line 73 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZOvEezon12qOaSBVk:-KGme6XLndqa6L5VMSvH:-499146009) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/thresholddetection/agent.py#L73)):*
Done.

---

*[services/core/ThresholdDetectionAgent/thresholddetection/agent.py, line 89 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZP4UUu-BE4K4Sgg-q:-KGme713hcdmFEb3R1BG:-499146009) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/thresholddetection/agent.py#L89)):*
Done.

---

*[services/core/ThresholdDetectionAgent/thresholddetection/agent.py, line 132 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGZPOkN9yI-5Km3NuHy:-KGme8I98BZUGBQ9r-Nh:-499146009) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/ThresholdDetectionAgent/thresholddetection/agent.py#L132)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/482)*

**Comment by craig8** [comment]
Reviewed 1 of 5 files at r3.
Review status: 4 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[services/core/SysMonAgent/sysmon/agent.py, line 87 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGYqDftvI3JOYi_aQwE:-KGnF8ERAZx98Lbyh6di:1290461313) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/sysmon/agent.py#L87)):*
Per our discussion offline build an rpc method "reconfigure" which takes **kwargs and allows reconfiguration of the agent.  I would assume that this would need to have manager or local platform priv. in order for this to work but that's something to discuss later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/482)*

**Comment by craig8** [comment]
Reviewed 3 of 5 files at r3.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/482)*

**Comment by zbeech** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[services/core/SysMonAgent/sysmon/agent.py, line 87 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/482#-KGYqDftvI3JOYi_aQwE:-KH0Dz9t2BlpMfNpQz6T:1053795602) ([raw file](https://github.com/volttron/volttron/blob/10e51d1562ea78447fa255ddd3948efd54192bad/services/core/SysMonAgent/sysmon/agent.py#L87)):*
I added the reconfigure(**kwargs) RPC method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/482)*

**Comment by craig8** [comment]
Reviewed 1 of 3 files at r2.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/482)*

**Comment by craig8** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/482)*

**Pull request merged**
