### PR TITLE
Feature/heartbeat status#440

### PR DESCRIPTION
**Pull request by craig8**
Please have a look at the code and tests and see if I missed anything.

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/441)

### CODE REVIEW

**Comment by mikeroup** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 80 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6AFzfpWeHt7O3rHw:-KEI6AFzfpWeHt7O3rHx:-1699965766) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L80)):*
This line can be removed. Assign the default status to self._status instead of None.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 88 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6ISZ4dWjlwmSI7fy:-KEI0jmm3PXWP4zPjU4v:14808884) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L88)):*
Redundant default parameter 'context'. set_status() passes context to this function.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 90 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI022haTNhLDBQLnyk:-KEI022haTNhLDBQLnyl:601404728) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L90)):*
Why is STATUS allowed as a prefix and a suffix?

---

*[volttron/platform/vip/agent/subsystems/health.py, line 94 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI4WmTh6u-H625Gobz:-KEI4WmTh6u-H625Goc-:869984090) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L94)):*
CURRENT_STATUS variable used here but not on line 108.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 95 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6wFjFsACF3cf8At2:-KEI6wFkPGK3UcGPW7vf:538727061) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L95)):*
Actually all three of these variables are only used once in this file.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 105 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI3QErbUgt6gn195vg:-KEI3QErbUgt6gn195vh:1501354573) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L105)):*
'Context' isn't clear. It this just a message describing the good/bad/unknown status?

---

*[volttron/platform/vip/agent/subsystems/health.py, line 113 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI31OPFMXcrKID_yQp:-KEI31OPFMXcrKID_yQq:2089210836) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L113)):*
Why not add a heartbeat.restart() method?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/441)*

**Comment by craig8** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 80 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6AFzfpWeHt7O3rHw:-KEI8Jc_j-yNVBedbL9j:1082373523) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L80)):*
No because then you don't have the timestamp.  The self._status is a dictionary not a simple string.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 90 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI022haTNhLDBQLnyk:-KEI8tSb6M2DbCWqpFf3:242181885) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L90)):*
Why not?  it's just an alias.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 95 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6wFjFsACF3cf8At2:-KEI9UKVKwbHXbGeTLqU:1314113592) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L95)):*
Your point being?

---

*[volttron/platform/vip/agent/subsystems/health.py, line 105 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI3QErbUgt6gn195vg:-KEI9cAg2S580EoQ8Jk7:12151085) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L105)):*
That is the current thought.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 113 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI31OPFMXcrKID_yQp:-KEI9mM3zayd0iBQyiTf:2020028806) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L113)):*
True that would work.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/441)*

**Comment by craig8** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 80 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6AFzfpWeHt7O3rHw:-KEIFeeMRvktoItBSLu_:-28945659) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L80)):*
In addition having it here makes the logic in set_status easier.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 88 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6ISZ4dWjlwmSI7fy:-KEIFw7LQfrDbUhEulvB:308399617) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L88)):*
Oh so you think I should remove the None?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/441)*

**Comment by craig8** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 88 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6ISZ4dWjlwmSI7fy:-KEIK2jFdcDnfFSKZPue:-982602161) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L88)):*
Actually it is necessary because of the call in the constructor of the object. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/441)*

**Comment by mikeroup** [comment]
Review status: 1 of 4 files reviewed at latest revision, 7 unresolved discussions.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 80 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6AFzfpWeHt7O3rHw:-KEIIEDxhra3ySyNyE68:1213958363) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L80)):*
I don't get why _status is set to None then we call a function to set it to what it should actually be. 

The timestamp call is in the dictionary assignment in _update_status.

Neither set_status() nor _update_status() would have to change.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 88 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6ISZ4dWjlwmSI7fy:-KEIKdVZhWdVdmtStv5s:1516193271) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L88)):*
Which I don't think should be there.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 90 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI022haTNhLDBQLnyk:-KEIJkYcTrIVpHc-6TOY:-1628333106) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L90)):*
We could sort attribute names to help people who can't spell but that doesn't mean we should.

---

*[volttron/platform/vip/agent/subsystems/health.py, line 95 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/441#-KEI6wFjFsACF3cf8At2:-KEIKmfLITasep3hXlzE:-540241257) ([raw file](https://github.com/volttron/volttron/blob/2d5a8cd0027db050c9fb49fca3fdded79a43a3a5/volttron/platform/vip/agent/subsystems/health.py#L95)):*
It's a level of indirection that isn't necessary since self._status is 'private'. The color difference is a nice bonus too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/441)*

**Comment by mikeroup** [comment]
Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/441)*

**Pull request merged**
