### PR TITLE
Updated vc vcp

### PR DESCRIPTION
**Pull request by craig8**
VC does not request to have the devices subtopic published to it any longer.
Instances now respond with instance name in the json response
Various other fixes.
Config store is used to full effect in both vc and vcp

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/1479)

### CODE REVIEW

**Comment by jhaack** [comment]
Reviewed 23 of 87 files at r1.
Review status: 23 of 69 files reviewed at latest revision, 1 unresolved discussion.

---

*[services/core/DataMover/config, line 3 at r1](https://reviewable.io:443/reviews/volttron/volttron/1479#-KtsZw7KL5NwgMDPgcYB:-KtsZw7KL5NwgMDPgcYC:b-bq97qt) ([raw file](https://github.com/volttron/volttron/blob/aedc671640b88952a6379f44ce97ac884392115d/services/core/DataMover/config#L3)):*
> ```
> {
>     "destination-vip": "tcp://127.0.0.1:22916",
>     "destination-serverkey": "wNRkx-zOPgQMvaiv6IORiJukVc5DijJ5gexj_Ga_qh0",
> ```

Take out key. Makes it more obvious it needs to be replaced

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/1479)*

**Comment by craig8** [comment]
Review status: 23 of 69 files reviewed at latest revision, 1 unresolved discussion.

---

*[services/core/DataMover/config, line 3 at r1](https://reviewable.io:443/reviews/volttron/volttron/1479#-KtsZw7KL5NwgMDPgcYB:-KtseniQ6aiY1Xk-cOEj:b-qr4dj7) ([raw file](https://github.com/volttron/volttron/blob/aedc671640b88952a6379f44ce97ac884392115d/services/core/DataMover/config#L3)):*
<details><summary><i>Previously, jhaack wrote…</i></summary><blockquote>

Take out key. Makes it more obvious it needs to be replaced
</blockquote></details>

so you want empty string or "<serverkey>"
I will assume serverkey.....should I do the same with the tcp address?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/1479)*

**Comment by craig8** [comment]
Review status: 22 of 69 files reviewed at latest revision, 1 unresolved discussion.

---

*[services/core/DataMover/config, line 3 at r1](https://reviewable.io:443/reviews/volttron/volttron/1479#-KtsZw7KL5NwgMDPgcYB:-KtsgK6YModETVZOra1-:b-896fix) ([raw file](https://github.com/volttron/volttron/blob/aedc671640b88952a6379f44ce97ac884392115d/services/core/DataMover/config#L3)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary><blockquote>

so you want empty string or "<serverkey>"
I will assume serverkey.....should I do the same with the tcp address?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/1479)*

**Comment by jhaack** [comment]
Reviewed 2 of 87 files at r1, 1 of 1 files at r2.
Review status: 25 of 69 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/1479)*

**Pull request merged**
