### PR TITLE
Feature/better vip id

### PR DESCRIPTION
**Pull request by kmonson**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/672)

### CODE REVIEW

**Comment by craig8** [comment]
Reviewed 5 of 13 files at r1, 4 of 17 files at r3, 20 of 29 files at r5.
Review status: 29 of 39 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/source/specifications/agent-vip-id.rst, line 1 \[r5\]](https://reviewable.io:443/reviews/volttron/volttron/672#-KNonqGR0EH64GAC1LCO:-KNonqGR0EH64GAC1LCP:-887214376) ([raw file](https://github.com/volttron/volttron/blob/8aa6f9bcb34dd7f8cbbe4804be83467ce8031606/docs/source/specifications/agent-vip-id.rst#L1)):*
> ```reStructuredText
> Agent VIP ID Assignment Specification
> ```

ID to IDENTITY...since we are using IDENTITY within the text

---

*[services/core/ActuatorAgent/actuator/agent.py, line 561 \[r5\]](https://reviewable.io:443/reviews/volttron/volttron/672#-KNoqZoyQo7m4d3lw9y4:-KNoqZozZjyHqXsFCt0i:1222600722) ([raw file](https://github.com/volttron/volttron/blob/8aa6f9bcb34dd7f8cbbe4804be83467ce8031606/services/core/ActuatorAgent/actuator/agent.py#L561)):*
> ```Python
>                  driver_vip_identity='platform.driver', **kwargs):
> 
>         super(ActuatorAgent, self).__init__(identity='platform.actuator', **kwargs)
> ```

I thought we didn't need this specified here?

---

*[volttron/platform/main.py, line 597 \[r5\]](https://reviewable.io:443/reviews/volttron/volttron/672#-KNosjrZwzuzCOaUdnx5:-KNosjr_nADQKxTwZ8Ns:-1459642173) ([raw file](https://github.com/volttron/volttron/blob/8aa6f9bcb34dd7f8cbbe4804be83467ce8031606/volttron/platform/main.py#L597)):*
> ```Python
>     os.environ['VOLTTRON_HOME'] = volttron_home
> 
>     #Remove AGENT_VIP_ID if it exists.
> ```

IDENTITY

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/672)*

**Comment by craig8** [comment]
@kmonson if you take a look through reviewable you can see all of the places that I wanted to make sure that we needed the identity to super.  I know you mentioned it but wanted to make clear it is necesssary.  Otherwise this is almost ready to be merged.

**Comment by kmonson** [comment]
Yes, it is needed if you run from the command line and the environment variable is not set. Otherwise in that case the identity will be random. As these are all service agents we need to specify an identity to fall back on.

---

Review status: 29 of 39 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[services/core/ActuatorAgent/actuator/agent.py, line 561 \[r5\]](https://reviewable.io:443/reviews/volttron/volttron/672#-KNoqZoyQo7m4d3lw9y4:-KNrTCqqqf-ij4HIG9F8:-413884875) ([raw file](https://github.com/volttron/volttron/blob/8aa6f9bcb34dd7f8cbbe4804be83467ce8031606/services/core/ActuatorAgent/actuator/agent.py#L561)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> I thought we didn't need this specified here?
</details>
This is only needed if you run the actuator from the command line. This is the fallback if the environment variable does not exist.  Otherwise the identity end up being random.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/672#-:-KNrToVo82UaQwf9Vbxl:1285876118)*

**Comment by craig8** [comment]
Review status: 29 of 39 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/source/specifications/agent-vip-id.rst, line 1 \[r5\]](https://reviewable.io:443/reviews/volttron/volttron/672#-KNonqGR0EH64GAC1LCO:-KNsCQ-QocfyQ1bRHbMU:792833098) ([raw file](https://github.com/volttron/volttron/blob/8aa6f9bcb34dd7f8cbbe4804be83467ce8031606/docs/source/specifications/agent-vip-id.rst#L1)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> ID to IDENTITY...since we are using IDENTITY within the text
</details>
The sentence above should change to

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/672)*

**Comment by craig8** [comment]
Reviewed 1 of 13 files at r1, 7 of 29 files at r5, 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/672)*

**Pull request merged**
