### PR TITLE
removed unused import - #2997

### PR DESCRIPTION
**Pull request by schandrika**

### CODE REVIEW

**Comment by craig8** [comment]
Please test this before putting it up

```
(volttron) gridappsd@gridappsd_dev_2004:/repos/volttron-develop$ volttron -vv
Traceback (most recent call last):
  File "/repos/volttron-develop/env/bin/volttron", line 11, in <module>
    load_entry_point('volttron', 'console_scripts', 'volttron')()
  File "/repos/volttron-develop/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/repos/volttron-develop/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/repos/volttron-develop/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/repos/volttron-develop/env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/repos/volttron-develop/volttron/platform/main.py", line 84, in <module>
    from volttron.platform.instance_setup import _update_config_file
  File "/repos/volttron-develop/volttron/platform/instance_setup.py", line 65, in <module>
    from volttron.utils.rmq_setup import setup_rabbitmq_volttron
  File "/repos/volttron-develop/volttron/utils/rmq_setup.py", line 66, in <module>
    from volttron.platform.auth.auth_protocols.auth_rmq import RMQConnectionAPI
  File "/repos/volttron-develop/volttron/platform/auth/auth_protocols/auth_rmq.py", line 29, in <module>
    class RMQClientParameters(Parameters):
  File "/repos/volttron-develop/volttron/platform/auth/auth_protocols/auth_rmq.py", line 35, in RMQClientParameters
    connection_params: pika.ConnectionParameters = None
NameError: name 'pika' is not defined
```

**Comment by schandrika** [comment]
I tested on a clean env. With just python3 bootstrap.py --force and volttron started without error. Does default bootstrap.py install pika?

**Comment by craig8** [comment]
No it doesn't install pika by default.  I tested on a clean env without the need of --force.

**Comment by schandrika** [comment]
I assumed --force would remove existing packages. My bad. 
Manually deleted env and tested and fixed imports. Volltron starts fine and I am able to do vctl and vcfg commands without any error

**Review by shwethanidd — APPROVED** [review]

**Pull request merged**
