### PR TITLE
merge jchap/chartsave into releases/3.5rc1

### PR DESCRIPTION
**Pull request by jchap-pnnl**
The README file at VolttronCentral/ui-src probably still needs work. We can include it as is and consider it a draft, or we can revise it before merging.

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/660)

### CODE REVIEW

**Comment by jchap-pnnl** [comment]
Dadgummit, Craig, quit working on your vacation!

**Comment by craig8** [comment]
Reviewed 14 of 19 files at r1.
Review status: 12 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/source/core_services/control/VOLTTRON-Config.rst, line 3 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xyKbDCU2PVDsdGnd:-KN8xyKbDCU2PVDsdGne:-1004696781) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/core_services/control/VOLTTRON-Config.rst#L3)):*
> ```reStructuredText
> .. _VOLTTRON-Config:
> VOLTTRON Config
> =====================
> ```

The ==== should end at the end of the title.

---

*[docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst, line 3 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xtC1895K1XLH-MJb:-KN8xtC1895K1XLH-MJc:-1004696781) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst#L3)):*
> ```reStructuredText
> .. _Eclipse-Dev-Environment:
> Eclipse Development Environment
> ===================================
> ```

The ==== should end at the end of the title.

---

*[docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst, line 119 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xhA6U6ywS-KiN4Lf:-KN8xhA6U6ywS-KiN4Lg:-1618152589) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst#L119)):*
> ```reStructuredText
> .. _Execute-Volttron-From-Shell:
> Execute VOLTTRON Through Shell
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

The ~~~~ should end at the end of the title.

---

*[docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst, line 132 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xqvXzU_MVMRthJrb:-KN8xqvXzU_MVMRthJrc:-1618152589) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst#L132)):*
> ```reStructuredText
> 
> Execute VOLTTRON Through Eclipse
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

The ~~~~ should end at the end of the title.

---

*[docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst, line 31 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8yTraKtT0Zw8BIIlS:-KN8yTraKtT0Zw8BIIlT:-1618152589) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst#L31)):*
> ```reStructuredText
> Running the Demo
> ~~~~~~~~~~~~~~~~~
> ```

The ~~~~ should end at the end of the title.

---

*[docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst, line 78 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8yYLxEslaDbAhtloX:-KN8yYLyXlkXPlo_C7xA:414323704) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst#L78)):*
> ```reStructuredText
> details on how to configure the agent for your specific use case.
> 
> Log In
> ```

The ----- should end at the end of the title.

---

*[docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst, line 95 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8ybnQmCS2dxlGLq20:-KN8ybnQmCS2dxlGLq21:318356854) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst#L95)):*
> ```reStructuredText
> 
> Platforms Tree
> ~~~~~~~~~~~~~~~~~
> ```

The --- should end at the end of the title. et all on this page.

---

*[services/core/VolttronCentral/ui-src/js/README, line 47 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8z-BdAM317GBNu3-o:-KN8z-BeQXUXyPFKW0oi:117930698) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/services/core/VolttronCentral/ui-src/js/README#L47)):*
> ```
> Routes
> 
> React-Router is used to handle loading and unloading of pages within the app. Pages and their paths are defined as routes in app.jsx and can be accessed through React-Router links placed in components.
> ```

Perhaps go through the getting to the compiled code.  Layout of the ui-source as another possibility

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/660)*

**Comment by jchap-pnnl** [comment]
Review status: 12 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/source/core_services/control/VOLTTRON-Config.rst, line 3 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xyKbDCU2PVDsdGnd:-KN9-dhy-ZvpzTZsReEp:1099262812) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/core_services/control/VOLTTRON-Config.rst#L3)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> The ==== should end at the end of the title.
</details>
Isn't this immaterial? The === just needs to be as long as the text to work. It's not visible, so doesn't matter if it's longer. It's like saying there's too much whitespace.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/660)*

**Comment by craig8** [comment]
Review status: 12 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/source/core_services/control/VOLTTRON-Config.rst, line 3 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xyKbDCU2PVDsdGnd:-KN92ZMVwYgw4nqWa_Zj:-375270975) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/core_services/control/VOLTTRON-Config.rst#L3)):*
<details><summary><i>Previously, jchap-pnnl wrote…</i></summary>
> Isn't this immaterial? The === just needs to be as long as the text to work. It's not visible, so doesn't matter if it's longer. It's like saying there's too much whitespace.
</details>
I believe that they throw a warning when you build it locally.  We want to have a minimal amount of chatter when running the make html so that we can see the real issues. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/660)*

**Comment by craig8** [comment]
Review status: 12 of 16 files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/source/core_services/control/VOLTTRON-Config.rst, line 3 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xyKbDCU2PVDsdGnd:-KN92nVPtJc5bQg4A6GI:1152261023) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/core_services/control/VOLTTRON-Config.rst#L3)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> I believe that they throw a warning when you build it locally.  We want to have a minimal amount of chatter when running the make html so that we can see the real issues. 
</details>
Though you are right they aren't displayed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/660)*

**Comment by jchap-pnnl** [comment]
Review status: 11 of 17 files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/source/core_services/control/VOLTTRON-Config.rst, line 3 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xyKbDCU2PVDsdGnd:-KN9JQufBp4jcfJzF48S:-499146009) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/core_services/control/VOLTTRON-Config.rst#L3)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> Though you are right they aren't displayed.
</details>
Done.

---

*[docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst, line 3 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xtC1895K1XLH-MJb:-KN9JY4d66pwiu6x65je:-499146009) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst#L3)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> The ==== should end at the end of the title.
</details>
Done.

---

*[docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst, line 119 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xhA6U6ywS-KiN4Lf:-KN9JYinGrMKwy9naDMM:-499146009) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst#L119)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> The ~~~~ should end at the end of the title.
</details>
Done.

---

*[docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst, line 132 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8xqvXzU_MVMRthJrb:-KN9JZSfaSQEp-DSpe94:-499146009) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/eclipse/Eclipse-Dev-Environment.rst#L132)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> The ~~~~ should end at the end of the title.
</details>
Done.

---

*[docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst, line 31 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8yTraKtT0Zw8BIIlS:-KN9J_Ajjo1mHM6IvFmJ:-499146009) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst#L31)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> The ~~~~ should end at the end of the title.
</details>
Done.

---

*[docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst, line 78 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8yYLxEslaDbAhtloX:-KN9J_j2Z1Ugrlfou5Uh:-499146009) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst#L78)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> The ----- should end at the end of the title.
</details>
Done.

---

*[docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst, line 95 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8ybnQmCS2dxlGLq20:-KN9JaJeDW1lrpE1FEq9:-499146009) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst#L95)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> The --- should end at the end of the title. et all on this page.
</details>
Done.

---

*[services/core/VolttronCentral/ui-src/js/README, line 47 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN8z-BdAM317GBNu3-o:-KN9Jc4l4NknCNzh8eXl:-499146009) ([raw file](https://github.com/volttron/volttron/blob/90cb2fec48d4c7211a31fd2687727be16ffa4f33/services/core/VolttronCentral/ui-src/js/README#L47)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> Perhaps go through the getting to the compiled code.  Layout of the ui-source as another possibility
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/660)*

**Comment by craig8** [comment]
Reviewed 2 of 19 files at r1, 4 of 5 files at r2.
Review status: 16 of 17 files reviewed at latest revision, 7 unresolved discussions.

---

*[services/core/VolttronCentral/ui-src/js/README, line 68 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN9L4rrec4nnrFrd4xz:-KN9L4rrec4nnrFrd4y-:952826382) ([raw file](https://github.com/volttron/volttron/blob/bfabac0717984d3e615dfe7da3c9aca9a506acb2/services/core/VolttronCentral/ui-src/js/README#L68)):*
> ```
> 
> 	npm install
> ```

Do we assume that they have installed nodejs or should we mention that here as well?  I talked to a guy yesterday that was going to do stuff in php...which obviously is not client side, however he didn't know what nodejs was nor that npm was a package manager for it...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/660)*

**Comment by jchap-pnnl** [comment]
Review status: 16 of 17 files reviewed at latest revision, 7 unresolved discussions.

---

*[services/core/VolttronCentral/ui-src/js/README, line 68 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/660#-KN9L4rrec4nnrFrd4xz:-KN9NXtFbEUT4a38pX7O:274907840) ([raw file](https://github.com/volttron/volttron/blob/bfabac0717984d3e615dfe7da3c9aca9a506acb2/services/core/VolttronCentral/ui-src/js/README#L68)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> Do we assume that they have installed nodejs or should we mention that here as well?  I talked to a guy yesterday that was going to do stuff in php...which obviously is not client side, however he didn't know what nodejs was nor that npm was a package manager for it...
</details>
Fair enough. I added info saying to make sure nodejs is installed so npm is available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/660)*

**Comment by craig8** [comment]
Reviewed 1 of 5 files at r2.
Review status: 16 of 17 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/660)*

**Comment by craig8** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/660)*

**Pull request merged**
