### PR TITLE
Added volttron_home being passed to service agents

### PR DESCRIPTION
**Pull request by craig8**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/721)

### CODE REVIEW

**Comment by craig8** [comment]
@zbeech I am adding you for comment on this.  I was going to add volttron_home to the AuthFile to get rid of the global dependence on VOLTTRON_HOME.  The goal is agents that start with the platform or installed on the platform will have volttron_home sent to them as an argument.  So the only one who should actually use the os.environ.get('VOLTTRON_HOME') is on the server and in vip_main.

So how do we modify your AuthFile function to make this happen?

**Comment by zbeech** [comment]
@craig8 I think we should add RPC calls to AuthService that provide access to AuthFile functionality, rather than calling AuthFile directly. That way AuthService can provide VOLTTRON_HOME to AuthFile.

**Comment by craig8** [comment]
@zbeech I agree...actually I am kinda surprised that we haven't done that already.  The thing is that blocking the caller with the privilege would require that the local interface be tcp based, which isn't a game killer just something that we need to be aware of.  Say instead of using ipc sockets we default to tcp://127.0.01:22916 or something. 

@kmonson  do you have any thought's on having a tcp address as "local" and doing away with ipc?

**Comment by craig8** [comment]
Merged without pushing to craig8/vip-main

**Pull request closed without merging**
