### PR TITLE
Bug fixes and updates to vcfg rabbitmq federation and shovel commands

### PR DESCRIPTION
**Pull request by shwethanidd**
# Description

1. Fixes all the review comments for federation and shovel connections (see attachment)
2. Contains new pytests for federation and shovel
3. Removed datamover reference in readme for multi-platform connection for rabbitmq

[federation_shovel_review_comments.xlsx](https://github.com/VOLTTRON/volttron/files/6601642/federation_shovel_review_comments.xlsx)

### CODE REVIEW

**Comment by schandrika** [comment]
```
(volttron) volttron@volttron1:~/git/myvolttron$ vcfg rabbitmq --help
usage: vcfg rabbitmq [-h] [--max-retries MAX_RETRIES] [--config CONFIG]
                     installation-type

positional arguments:
  installation-type     Rabbitmq option for installation. Installation type
                        can be single|federation|shovel

optional arguments:
  -h, --help            show this help message and exit
  --max-retries MAX_RETRIES
                        Optional Max retry attempt
  --config CONFIG       Optional path to rabbitmq config yml
```

What does --max-retries do for vcfg rabbitmq single ? Isn't it valid only for federation or shovel for csr approval

**Comment by craig8** [comment]
Can you change Jira/3 to something meaningful to people outside of the lab.

**Comment by schandrika** [comment]
`(volttron) volttron@volttron2:~/git/myvolttron$ vcfg rabbitmq federation --config /home/volttron/rmq_federation.yml
`
fails with the below error

(volttron) volttron@volttron2:~/git/myvolttron$ vcfg rabbitmq federation --config /home/volttron/rmq_federation.yml


Your VOLTTRON_HOME currently set to: /home/volttron/vhome_rmq2

Is this the volttron you are attempting to setup? [Y]: y
Name of this volttron instance: [volttron1]: volttron2
ERROR: Error opening /home/volttron/vhome_rmq2/rabbitmq_config.yml. Please create a rabbitmq_config.yml file in your volttron home. If you want to point to a volttron home other than /home/volttron/vhome_rmq2 please set it as the environment variable VOLTTRON_HOME
ERROR:
For single setup, configuration file must at least contain host and ssl certificate details. For federation and shovel setup, config should contain details about the volttron instance with which communication needs to be established. Please refer to example config file at examples/configurations/rabbitmq/rabbitmq_config.yml
Traceback (most recent call last):
  File "/home/volttron/git/myvolttron/env/bin/vcfg", line 11, in <module>
    load_entry_point('volttron', 'console_scripts', 'vcfg')()
  File "/home/volttron/git/myvolttron/volttron/platform/config.py", line 588, in _main
    main()
  File "/home/volttron/git/myvolttron/volttron/platform/instance_setup.py", line 1048, in main
    process_rmq_inputs(vars(args))
  File "/home/volttron/git/myvolttron/volttron/platform/instance_setup.py", line 983, in process_rmq_inputs
    setup_rabbitmq_volttron(args_dict['installation-type'], verbose, instance_name=instance_name, max_retries=args_dict['max_retries'])
  File "/home/volttron/git/myvolttron/volttron/utils/rmq_setup.py", line 745, in setup_rabbitmq_volttron
    rmq_config.load_rmq_config()
  File "/home/volttron/git/myvolttron/volttron/utils/rmq_config_params.py", line 133, in load_rmq_config
    with open(self.volttron_rmq_config, 'r') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/volttron/vhome_rmq2/rabbitmq_config.yml'

**Comment by schandrika** [comment]
(volttron) volttron@volttron2:~/git/myvolttron$ vcfg rabbitmq federation

Your VOLTTRON_HOME currently set to: /home/volttron/vhome_rmq2

Is this the volttron you are attempting to setup? [Y]:
Name of this volttron instance: [volttron2]:
Number of upstream servers to configure: [1]:
Hostname of the upstream server:  volttron1
Port of the upstream server:  [5671]:
Virtual host of the upstream server:  [volttron]:

Do you have certificates signed by remote CA?  [N]:
Path to remote web interface:  [https://volttron1:8443]:
ERROR: Exception creating certs. invalid certificate path /home/volttron/vhome_rmq2/certificates/certs/volttron2-root-ca.crt
ERROR: invalid certificate path /home/volttron/vhome_rmq2/certificates/certs/volttron2-root-ca.crt

**Comment by schandrika** [comment]
> (volttron) volttron@volttron2:~/git/myvolttron$ vcfg rabbitmq federation
> 
> Your VOLTTRON_HOME currently set to: /home/volttron/vhome_rmq2
> 
> Is this the volttron you are attempting to setup? [Y]:
> Name of this volttron instance: [volttron2]:
> Number of upstream servers to configure: [1]:
> Hostname of the upstream server: volttron1
> Port of the upstream server: [5671]:
> Virtual host of the upstream server: [volttron]:
> 
> Do you have certificates signed by remote CA? [N]:
> Path to remote web interface: [https://volttron1:8443]:
> ERROR: Exception creating certs. invalid certificate path /home/volttron/vhome_rmq2/certificates/certs/volttron2-root-ca.crt
> ERROR: invalid certificate path /home/volttron/vhome_rmq2/certificates/certs/volttron2-root-ca.crt

I figured what causes this issue. I had forgotten to do vcfg rabbitmq single before setting up federation.  Good to add a reminder in documentation or may be easy enough to add a check in code too - we have have to check if vhome/rabbitmq_config.yml right?

**Comment by shwethanidd** [comment]
Fixes #2718

**Pull request merged**
