### PR TITLE
Added code for restricting vip identities

### PR DESCRIPTION
**Pull request by craig8**
Added documentation for the valid characters for identities.

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/733)

### CODE REVIEW

**Comment by craig8** [comment]
Well that's not good...seems I broke all the tests ;).  I will fix and then let @kmonson know when it's ready.

**Comment by craig8** [comment]
Ok that's better go for it @kmonson

**Comment by kmonson** [comment]
I don't think we should try to enforce the identity rules in Agent or vip_main. We can mention in the spec that it's not recommended and that some services may not work for the Agent and leave it at that. We could put in a warning if you want. 

We should leave in all the other sanity checks at installation time of course.

**Comment by craig8** [comment]
I though that they s was what we discussed last week.  Did our thinking change?

**Comment by kmonson** [comment]
I don’t think we ever discussed where we were going to enforce this. Let’s talk about it tomorrow at work.

**Comment by craig8** [comment]
Closing this based upon feedback from @kmonson.  I will modify and re-submit.

**Pull request closed without merging**
