### PR TITLE
Feature/actuator timezone

### PR DESCRIPTION
**Pull request by schandrika**
made actuator request times timezone aware and defaulting to local timezone if provided time is naive
using utctimetuple in core for scheduling

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/645)

### CODE REVIEW

**Comment by craig8** [comment]
Reviewed 2 of 7 files at r2.
Review status: 2 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[services/core/ActuatorAgent/actuator/scheduler.py, line 76 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvaw5IzRNxrIlBqHaZ:-KKvaw5IzRNxrIlBqHa_:-2122262966) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/actuator/scheduler.py#L76)):*
> ```Python
> RequestResult = namedtuple('RequestResult', ['success', 'data', 'info_string'])
> DeviceState = namedtuple('DeviceState', ['agent_id', 'task_id', 'time_remaining'])
> utils.setup_logging()
> ```

The setup_logging here is not recommended since the process has already been setup in agent.py.  The logging.getLogger(__name__) will be sufficient.

---

*[services/core/ActuatorAgent/tests/test_actuator_pubsub.py, line 239 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvc8QWru6qJqePm8-f:-KKvc8QXB72jnbamQSLE:-1095583188) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/tests/test_actuator_pubsub.py#L239)):*
> ```Python
> 
> # def callback(self, peer, sender, bus, topic, headers, message):
> #     print("*************In callback")
> ```

Extraneous code that wasn't in the repo before.  Please remove.

---

*[services/core/ActuatorAgent/tests/test_actuator_pubsub.py, line 259 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvcEgF9PqUq7kLtbNs:-KKvcEgGQd9QIw68Aool:1741755365) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/tests/test_actuator_pubsub.py#L259)):*
> ```Python
>         publish_agent_v2.publish_json(topic, header, message)
> 
> @pytest.mark.dev
> ```

Remove dev mark as you aren't developing this test any longer.

---

*[services/core/ActuatorAgent/tests/test_actuator_pubsub.py, line 336 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvcKwWYSqJHpXpw99z:-KKvcKwWYSqJHpXpw9A-:680755196) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/tests/test_actuator_pubsub.py#L336)):*
> ```Python
>     assert result_header['type'] == 'CANCEL_SCHEDULE'
> 
> #@pytest.mark.dev
> ```

Remove extraneous comment

---

*[volttron/platform/agent/base_historian.py, line 1089 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvcUnImkVonEAg5Sk1:-KKvcUnImkVonEAg5Sk2:-1668941581) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/volttron/platform/agent/base_historian.py#L1089)):*
> ```Python
> from dateutil.tz import gettz
> from tzlocal import get_localzone
> ```

Perhaps would be a good place to document why we are using this rather than what was in just the datetime.tz object.

---

*[volttron/platform/agent/utils.py, line 339 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvcj7K8A9RllghBDou:-KKvcj7K8A9RllghBDov:-911659940) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/volttron/platform/agent/utils.py#L339)):*
> ```Python
> 
> def get_utc_seconds_from_epoch(timestamp=datetime.now(tz=tzutc())):
>     if timestamp.tzinfo is None:
> ```

Document the input and output of this function in rtd format.

---

*[volttron/platform/agent/utils.py, line 350 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvcpbGRRGktDXP-oKR:-KKvcpbGRRGktDXP-oKS:887757972) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/volttron/platform/agent/utils.py#L350)):*
> ```Python
> 
> def process_timestamp(timestamp_string, topic=''):
>     if timestamp_string is None:
> ```

Document process_timestamp.  What does it mean to process a timestamp.  

---

*[volttron/platform/vip/agent/core.py, line 383 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvd2TiuINEmp-BgSj1:-KKvd2TiuINEmp-BgSj2:1503153526) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/volttron/platform/vip/agent/core.py#L383)):*
> ```Python
>         if hasattr(deadline, 'timetuple'):
>             #deadline = time.mktime(deadline.timetuple())
>             deadline = utils.get_utc_seconds_from_epoch(deadline)
> ```

Remove commented out code.

---

*[volttron/platform/vip/agent/core.py, line 392 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvd-y0_BC3rR3GQvtw:-KKvd-y0_BC3rR3GQvtx:1503153526) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/volttron/platform/vip/agent/core.py#L392)):*
> ```Python
>     def schedule(cls, deadline, *args, **kwargs):   # pylint: disable=no-self-argument
>         if hasattr(deadline, 'timetuple'):
>             #deadline = time.mktime(deadline.timetuple())
> ```

Remove commented out code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/645)*

**Comment by schandrika** [comment]
Review status: 2 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[services/core/ActuatorAgent/actuator/scheduler.py, line 76 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvaw5IzRNxrIlBqHaZ:-KKzi9YlSRuxkzAdOnWp:1847423181) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/actuator/scheduler.py#L76)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> The setup_logging here is not recommended since the process has already been setup in agent.py.  The logging.getLogger(__name__) will be sufficient.
</details>
scheduler.py is not an Agent. It is used by the actuator agent.py. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/645)*

**Comment by schandrika** [comment]
Review status: 1 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[services/core/ActuatorAgent/actuator/scheduler.py, line 76 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvaw5IzRNxrIlBqHaZ:-KKzrrAhPq8i3qeZ1sW9:278740752) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/actuator/scheduler.py#L76)):*
<details><summary><i>Previously, schandrika wrote…</i></summary>
> scheduler.py is not an Agent. It is used by the actuator agent.py. 
</details>
Removed setup_logging from actuator agent module. Did not remove it in scheduler.py. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/645)*

**Comment by craig8** [comment]
Reviewed 1 of 7 files at r2, 3 of 5 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[services/core/ActuatorAgent/actuator/scheduler.py, line 76 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvaw5IzRNxrIlBqHaZ:-KL3D5w-7PTbGFdMGTsu:14618272) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/actuator/scheduler.py#L76)):*
<details><summary><i>Previously, schandrika wrote…</i></summary>
> Removed setup_logging from actuator agent module. Did not remove it in scheduler.py. 
</details>
It should be removed from here and not the main process for the agent.  The agent that starts the process should be the only place for setup_logging otherwise the logs in it will not work untile the scheduler is imported.  So if you do a test and try to log something before importing schedule.py that log will not go to the proper spot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/645)*

**Comment by schandrika** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[services/core/ActuatorAgent/actuator/scheduler.py, line 76 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvaw5IzRNxrIlBqHaZ:-KL3Mybi-XvtI8kzwkNn:-64626591) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/actuator/scheduler.py#L76)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> It should be removed from here and not the main process for the agent.  The agent that starts the process should be the only place for setup_logging otherwise the logs in it will not work untile the scheduler is imported.  So if you do a test and try to log something before importing schedule.py that log will not go to the proper spot.
</details>
Okay.  Would it then be better to do the setup in Base agent class. Then individual agents don't have to remember calling setup. We anyway do all module level imports first  before any log declarations so Agent class would be imported and log would be setup before core logic starts. Does that sound good?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/645)*

**Comment by craig8** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[services/core/ActuatorAgent/actuator/scheduler.py, line 76 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvaw5IzRNxrIlBqHaZ:-KL3NuimoXqwzpfK4Jpp:-936263838) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/actuator/scheduler.py#L76)):*
<details><summary><i>Previously, schandrika wrote…</i></summary>
> Okay.  Would it then be better to do the setup in Base agent class. Then individual agents don't have to remember calling setup. We anyway do all module level imports first  before any log declarations so Agent class would be imported and log would be setup before core logic starts. Does that sound good?
</details>
That's a good question.  I think for now no.  I want to be able to put something in the base agent or somewhere that will allow us to eventually have an rpc method to change the logging level.  I haven't thought about what that would look like yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/645)*

**Comment by schandrika** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[services/core/ActuatorAgent/actuator/scheduler.py, line 76 \[r2\]](https://reviewable.io:443/reviews/volttron/volttron/645#-KKvaw5IzRNxrIlBqHaZ:-KL3RF5updGC1YBGyDpD:1393007110) ([raw file](https://github.com/volttron/volttron/blob/ed796b582b3d3195c88a05412fdae589626f7c21/services/core/ActuatorAgent/actuator/scheduler.py#L76)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> That's a good question.  I think for now no.  I want to be able to put something in the base agent or somewhere that will allow us to eventually have an rpc method to change the logging level.  I haven't thought about what that would look like yet.
</details>
okay. Changed. Also ran a quick format as there were multiple lines longer than 80 characters

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/645)*

**Comment by craig8** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/645)*

**Pull request merged**
