### PR TITLE
Added handler for devices that do not support use_read_multiple by de…

### PR DESCRIPTION
**Pull request by acedrew**
…fault

# Description

Automatically resolves situation where a device is configured to use_read_multiple but rejects read_multiple requests with the 'unrecognized-service' error.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Had device configured to use_read_multiple that was responding with  rejection errors and deployed code, scrapes happened successfully.

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by bonicim** [comment]
Hi @acedrew, 

What was the device configuration (i.e. bacnet config file) that triggered this RemoteError? I want to see if I can create an integ test for this case as part of my PR #2685  to add Bacnet integ tests, which we currently don't have.

**Comment by craig8** [comment]
@acedrew ping...

**Comment by acedrew** [comment]
It all depends on the end device, I believe it just gave a generic reject with reason '9' which I looked up in the BACnet standard as unrecognized service. The only config requirement is leaving 'use_read_multiple' as the default, 'true' and trying to communicate with a device that does not support read multiple and fails with that specific error code.

**Comment by bonicim** [comment]
> It all depends on the end device, I believe it just gave a generic reject with reason '9' which I looked up in the BACnet standard as unrecognized service. The only config requirement is leaving 'use_read_multiple' as the default, 'true' and trying to communicate with a device that does not support read multiple and fails with that specific error code.

Thanks. I've tested this branch on the BACnet device that we have at the PNNL campus. The Platform Driver and BACnet driver behaved as expected. While this end device was not setup to simulate the conditions required to test this case (i.e. a device that does not support read multiple that fails with error code '9'), I was able to verify with confidence that this additional elseif clause did not negatively affect the behavior of the BACnet driver.

**Pull request merged**
