### PR TITLE
Fixes for revert errors

### PR DESCRIPTION
**Pull request by jhaack**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/648)

### CODE REVIEW

**Comment by craig8** [comment]
Reviewed 13 of 18 files at r1.
Review status: 13 of 18 files reviewed at latest revision, 2 unresolved discussions.

---

*[volttron/platform/web.py, line 298 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/648#-KL43Me_0iXIhq-2EB0c:-KL43MeaioPZbkoew2uZ:-21431893) ([raw file](https://github.com/volttron/volttron/blob/50203d51fd6d9141f99ad9f6d5494317013c09bd/volttron/platform/web.py#L298)):*
> ```Python
>         authentry = AuthEntry(
>             credentials="CURVE:{}".format(vcpublickey)
>         )
> ```

Remove as this is part of zach's cleanup.

---

*[volttron/platform/agent/base_historian.py, line 372 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/648#-KL43nY59_YMDzxwj82l:-KL43nY59_YMDzxwj82m:2039084335) ([raw file](https://github.com/volttron/volttron/blob/6d9d188c7db7502265f7637ff40030ba69a89099/volttron/platform/agent/base_historian.py#L372)):*
> ```Python
>     def _capture_record_data(self, peer, sender, bus, topic, headers,
>                              message):
>         _log.debug('Capture record data {}'.format(message))
> ```

Make this info with just the topic  or leave as debug with the message but remove the one below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/648)*

**Comment by craig8** [comment]
Reviewed 2 of 18 files at r1.
Review status: 15 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[volttrontesting/utils/platformwrapper.py, line 162 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/648#-KL44NS-sIR16qpQnSug:-KL44NS-sIR16qpQnSuh:-1658077781) ([raw file](https://github.com/volttron/volttron/blob/6d9d188c7db7502265f7637ff40030ba69a89099/volttrontesting/utils/platformwrapper.py#L162)):*
> ```Python
>         self.logit('Creating platform wrapper')
> 
>     def logit(self, message):
> ```

The self.logit is new stfuff....the prints are not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/648)*

**Comment by jhaack** [comment]
Review status: 15 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[volttron/platform/agent/base_historian.py, line 372 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/648#-KL43nY59_YMDzxwj82l:-KL47M4_Yxr0KfGOtTMI:676635175) ([raw file](https://github.com/volttron/volttron/blob/6d9d188c7db7502265f7637ff40030ba69a89099/volttron/platform/agent/base_historian.py#L372)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> Make this info with just the topic  or leave as debug with the message but remove the one below
</details>
Done

---

*[volttrontesting/utils/platformwrapper.py, line 162 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/648#-KL44NS-sIR16qpQnSug:-KL47Soy3hyB4nVfE9PM:1988604328) ([raw file](https://github.com/volttron/volttron/blob/6d9d188c7db7502265f7637ff40030ba69a89099/volttrontesting/utils/platformwrapper.py#L162)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> The self.logit is new stfuff....the prints are not.
</details>
Reverted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/648)*

**Comment by craig8** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/648)*

**Comment by craig8** [comment]
Reviewed 1 of 2 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[volttron/platform/__init__.py, line 67 \[r8\]](https://reviewable.io:443/reviews/volttron/volttron/648#-KLTh0-3s8T6qTFLarR0:-KLTh0-4X6hanj29DIWr:-1460541261) ([raw file](https://github.com/volttron/volttron/blob/14bcbaeb554972a2620845c299d73dc01f2d1fd8/volttron/platform/__init__.py#L67)):*
> ```Python
> 
> def set_home(home=None):
>     '''Set the home directory with user and variables expanded.
> ```

BAD don't use ''' for these pep-8 fail yes I know it's even below...I am passing this but for future :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/648)*

**Comment by craig8** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/648)*

**Pull request merged**
