### PR TITLE
DDS example agent

### PR DESCRIPTION
**Pull request by mikeroup**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/653)

### CODE REVIEW

**Comment by craig8** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

*[.gitmodules, line 3 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/653#-KLTeSmsf0uR9yjZjlFs:-KLTeSmtx4Vr8QGLuV_5:1192613247) ([raw file](https://github.com/volttron/volttron/blob/a868c632e8f97339cc8a0794f3e3a57747ee64be/.gitmodules#L3)):*
> ```
> [submodule "restricted/pnnl/volttron-restricted"]
> 	path = restricted/pnnl/volttron-restricted
> 	url = https://git.pnnl.gov/volttron/volttron-restricted
> ```

This actually needs to use a subtree rather than a modules.  I need to add that in the develop branch for our  applications as well.  See http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

We want to do the following: 

Unlike submodules, subtrees do not need any special
constructions (like .gitmodule files or gitlinks) be present in
your repository, and do not force end-users of your
repository to do anything special or to understand how subtrees
work. A subtree is just a subdirectory that can be
committed to, branched, and merged along with your project in
any way you want.

---

*[examples/DDSAgent/ddsagent/agent.py, line 4 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/653#-KLTfOErdkLOHBDn9XZ-:-KLTfOEsf0txPvkdLnhZ:-1458939892) ([raw file](https://github.com/volttron/volttron/blob/a868c632e8f97339cc8a0794f3e3a57747ee64be/examples/DDSAgent/ddsagent/agent.py#L4)):*
> ```Python
> # vim: set fenc=utf-8 ft=python sw=4 ts=4 sts=4 et:
> #
> # Copyright (c) 2015, Battelle Memorial Institute
> ```

copyright.

---

*[examples/DDSAgent/ddsagent/agent.py, line 90 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/653#-KLTfThl_0yozI1I7QwY:-KLTfThl_0yozI1I7QwZ:638969959) ([raw file](https://github.com/volttron/volttron/blob/a868c632e8f97339cc8a0794f3e3a57747ee64be/examples/DDSAgent/ddsagent/agent.py#L90)):*
> ```Python
>     @Core.periodic(1)
>     def publish_demo(self):
>         sample = {"shapesize": 30,
> ```

What does the publish demo do?

---

*[examples/DDSAgent/ddsagent/agent.py, line 105 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/653#-KLTfYNpOsASHeIu4pDj:-KLTfYNpOsASHeIu4pDk:-577282209) ([raw file](https://github.com/volttron/volttron/blob/a868c632e8f97339cc8a0794f3e3a57747ee64be/examples/DDSAgent/ddsagent/agent.py#L105)):*
> ```Python
>     @RPC.export
>     def read_from_dds(self, typename):
>         reader = self.reader[typename]
> ```

Please move the data access documentation from  where it is into the function doc string.

---

*[examples/DDSAgent/ddsagent/agent.py, line 133 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/653#-KLTgZmTC8b9GI-QA_Xp:-KLTgZmUOkwbtSV9q7QY:160841980) ([raw file](https://github.com/volttron/volttron/blob/a868c632e8f97339cc8a0794f3e3a57747ee64be/examples/DDSAgent/ddsagent/agent.py#L133)):*
> ```Python
>     @RPC.export
>     def write_to_dds(self, typename, sample):
>         writer = self.writer[typename]
> ```

Same as above 

---

*[examples/DDSAgent/ddsagent/rticonnextdds-connector, line 1 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/653#-KLTgeFFi1VBmL_Ji7wZ:-KLTgeFFi1VBmL_Ji7w_:1374117651) ([raw file](https://github.com/volttron/volttron/blob/a868c632e8f97339cc8a0794f3e3a57747ee64be/examples/DDSAgent/ddsagent/rticonnextdds-connector#L1)):*
> ```
> Subproject commit d6299be296dac11a7814547dc749bc06be74045d
> ```

I assume this will go away when using subtrees instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/653)*

**Comment by craig8** [comment]
Please add this agent to the general example agents.

**Comment by mikeroup** [comment]
@craig8 What do you mean by this?

**Comment by jhaack** [comment]
Redo this pull request from the latest develop branch

**Comment by craig8** [comment]
no I mean we shouldn't have the DDS code in our repo, but give directions on how to get it from their repo using the git subtree command.

**Comment by jhaack** [comment]
Redo the pull request with only the relevant files changed.

**Pull request closed without merging**
