### PR TITLE
Update mysqlfuncts and ci-integration config to let tests run on Trav…

### PR DESCRIPTION
**Pull request by bonicim**
# Description

Update mysqlfuncts level one integ tests and ci-integration directory to allow tests to run on Travis-CI and on the test-run-docker script. Initial testing only succeded on running tests using Pytest but not within a CI test framework. This PR allows these tests to be run on TravisCI. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I ran the tests on my throwaway Travis CI branch. The tests do run on Travis but they timeout due to test connection errors, most likely an issue with Mysqlconnector. However, that is out of the scope of this PR and will be addressed later down the road. The PR is to allow testing multiple versions of MySQL on TravisCI and locally. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bonicim** [comment]
Commit 3d69e55 addresses issue see in this [PR](https://github.com/bonicim/volttron/commit/dbc938a1edf2e9e6b0a3099f32f0b9ec9f9b16b5).

**Comment by bonicim** [comment]
Reverting commit 3d69e55 because I was mixing formatting changes in with logic changes; formatting changes should be in its own dedicated PR.

**Comment by craig8** [comment]
please add
import logging
logging.getLogger("urllib3.connectionpool").setLevel(logging.DEBUG)

To the top of the test files.

**Comment by craig8** [comment]
@bonicim is this still in draft mode?

**Comment by bonicim** [comment]
bump @shwethanidd

**Pull request merged**
