### PR TITLE
Added toctree link to web-api documentation.

### PR DESCRIPTION
**Pull request by davidraker**
# Description

Added link in index.rst for web-api documentation.

Fixes # (issue)
#2983

## Type of change

- [ ] documentation

# How Has This Been Tested?

make html, then pull up in browser. Currently, this has the top-level link to the web-api documentation, but does not expand the menu on the left with sub-topics.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by craig8** [comment]
https://raw.githubusercontent.com/davidraker/volttron/web-api_documentation/docs/source/platform-features/security/volttron-security.rst

I believe that this at the bottom of the page will allow the expansion on the left

```
.. toctree::

   key-stores
   known-hosts-file
   running-agent-as-user

```

**Comment by davidraker** [comment]
I did do this in the platform-features/web-api/introduction.rst file, which is the one linked by the index.rst. It doesn't seem to be working for me, though.

**Comment by craig8** [comment]
after you did this, did you regenerate and then open in a cache free environment.  Are you using an actual server or just viewing the html....

like python -m http.server ... to serve the build/html directory.

**Comment by davidraker** [comment]
I was just visiting the file in a browser after regenerating the html. I thought I had force reloaded, but apparently I did not. I am getting a single sub entry. I should be able to debug why the second entry isn't showing up from here. Should this continue to expand down to nested levels, though, or stop at the second level down?

**Comment by craig8** [comment]
I think you should look at it from a user of the api and do what is best for them....I am not sure which way would be more beneficial.

**Comment by craig8** [comment]
After checking I think we should rename VUI to something more meaningful.
image

In addition, there needs to be some sort of link from the Web Framework down to the RESTful web interface.  This is perhaps outside the initial scope of this, however I think the link would be a good idea in this pr.

**Comment by craig8** [comment]
@davidraker is this ready for a review again?

**Comment by davidraker** [comment]
> @davidraker is this ready for a review again?

I believe it is now. I've added my last changes. I let it get stale, so I could be forgetting something, but after looking it over a bit, I haven't found anything missing. Let me know if you see anything obvious I've forgotten.

**Comment by craig8** [comment]
@davidraker when clicking on the authentication link on the RESTful web api page it doesn't seem to map into the tree.

**Pull request merged**
