### PR TITLE
Add tests for heartbeat subsystem

### PR DESCRIPTION
**Pull request by mikeroup**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/430)

### CODE REVIEW

**Comment by craig8** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[volttrontesting/testutils/test_platformwrapper.py, line 54 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/430#-KE7fc0B2QPDyMuWUpBe:-KE7fc0CYMAj_4p9j9ew:20088594) ([raw file](https://github.com/volttron/volttron/blob/4929cb1a7db7fb4bf5f200d9791f1c0ae1300555/volttrontesting/testutils/test_platformwrapper.py#L54)):*
Instead of using this while loop can we switch to using the gevent_polling function here?

https://github.com/VOLTTRON/volttron/blob/develop/volttrontesting/utils/utils.py

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/430)*

**Comment by mikeroup** [comment]
*[volttrontesting/testutils/test_platformwrapper.py, line 54 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/430#-KE7fc0B2QPDyMuWUpBe:-KE7kAJEvDZAYYkbDCAo:1484569895) ([raw file](https://github.com/volttron/volttron/blob/4929cb1a7db7fb4bf5f200d9791f1c0ae1300555/volttrontesting/testutils/test_platformwrapper.py#L54)):*
No reason not to. It just wasn't around in the branch where this was based.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/430)*

**Comment by craig8** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[volttrontesting/testutils/test_platformwrapper.py, line 54 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/430#-KE7fc0B2QPDyMuWUpBe:-KE7m1bP6iyZDDtua67F:-368625333) ([raw file](https://github.com/volttron/volttron/blob/4929cb1a7db7fb4bf5f200d9791f1c0ae1300555/volttrontesting/testutils/test_platformwrapper.py#L54)):*
Did I miss the commit where you took care of this?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/430)*

**Comment by mikeroup** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[volttrontesting/testutils/test_platformwrapper.py, line 54 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/430#-KE7fc0B2QPDyMuWUpBe:-KE7ojlDi3v_N0cNWTEM:1126602254) ([raw file](https://github.com/volttron/volttron/blob/4929cb1a7db7fb4bf5f200d9791f1c0ae1300555/volttrontesting/testutils/test_platformwrapper.py#L54)):*
Only if you can see into the future.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/430)*

**Pull request closed without merging**
