### PR TITLE
Cyberops + Matlab Docs

### PR DESCRIPTION
**Pull request by poorva1209**
- Added Syslog agent
- Added matlab documentation
- Added matlab example application

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/675)

### CODE REVIEW

**Comment by craig8** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[docs/source/devguides/walkthroughs/DrivenMatlabAgent-Walkthrough.rst, line 8 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/675#-KO8ge-H9wXE3OpHU63m:-KO8ge-IArHinXP7xEEz:-1545664297) ([raw file](https://github.com/volttron/volttron/blob/356526479bb1c862d1a863cebca40ed494727d23/docs/source/devguides/walkthroughs/DrivenMatlabAgent-Walkthrough.rst#L8)):*
> ```reStructuredText
> =========
> 
>     Matlab-Volttron integration allows Matlab application to receive
> ```

Volttron should be VOLTTRON in all of the instances of the documentation.

---

*[docs/source/devguides/walkthroughs/DrivenMatlabAgent-Walkthrough.rst, line 63 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/675#-KO8hDRpb9W1avMCng9_:-KO8hDRqEEyx1Cxt2NrP:-1666958639) ([raw file](https://github.com/volttron/volttron/blob/356526479bb1c862d1a863cebca40ed494727d23/docs/source/devguides/walkthroughs/DrivenMatlabAgent-Walkthrough.rst#L63)):*
> ```reStructuredText
> -------------
> 
> 1. Copy applications/pnnl/DrivenMatlabAgent/config\_waterheater.
> ```

Why config_waterheater?  Copy it to where?  the applications directory is no longer in the VOLTTRON repository.  So we need to do something different here.  

Eg add how to get the applications into the tree.

---

*[docs/source/devguides/walkthroughs/DrivenMatlabAgent-Walkthrough.rst, line 83 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/675#-KO8heloy-vB3A4adL1V:-KO8heloy-vB3A4adL1W:-653859032) ([raw file](https://github.com/volttron/volttron/blob/356526479bb1c862d1a863cebca40ed494727d23/docs/source/devguides/walkthroughs/DrivenMatlabAgent-Walkthrough.rst#L83)):*
> ```reStructuredText
> --------------------------
> 
> 1. Install and run VOLTTRON on same or different system than the one
> ```

Can't run it on the same system (unless in a vm) because VOLTTRON doesn't run in python 3.4

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/675)*

**Comment by craig8** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/675)*

**Comment by craig8** [comment]
Can you figur out what is going on with the errors in this commit? @poorva1209

**Comment by craig8** [comment]
@poorva1209 can you pull the new develop code...sorry there are some conflicts that when I pulled it I wasn't able tof ix them.

**Comment by poorva1209** [comment]
@craig8 - this branch is now merged with new develop code . Let me know if you still see conflicts.

**Pull request closed without merging**
