### PR TITLE
Update travis config

### LINKED ISSUE #1444: Upgrade .travis.yml file
End of life for precise so we should update the .travis.yml file to only build for trusty.  We should include higher versions of python e.g. 2.7.13 to see what effect that has.

In addition we need to add the databases to the build so that we test them on ci.

### PR DESCRIPTION
**Pull request by bonicim**
# Description

Update TravisCI config to run builds on Python 3.x and above. Add comments for clarity and reconfiguration. Although Xenial is the default OS, it is explicitly stated in the config to help beginners on TravisCI. 

This configuration takes advantage of TravisCI's [matrix expansion](https://docs.travis-ci.com/user/build-matrix/#matrix-expansion), in which certain keywords when combined will create separate jobs. 

In this case, the keywords `python` and `env` are the keywords that will create a certain number of jobs. Since the environment variables are labeled `global`, they will be used on every job. Thus, the number of jobs will be `python` X `env` (i.e. 3 X 1).

Fixes #1444

## Type of change

Please delete options that are not relevant.

- [x] Config change (non-breaking change which fixes an issue)

# How Has This Been Tested?
On my personal TravisCI dashboard, I ran this configuration. All builds passed. See screenshot. 
Screen Shot 2020-05-26 at 3 50 15 PM

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by shwethanidd** [comment]
@craig8 can you look at this?

**Comment by bonicim** [comment]
I added bionic as requested. 

The current config creates 6 jobs: Python (3.6-8) x Ubuntu (xenial and bionic)

I've tested the config on my own TravisCI and it succeeded. See screenshot below:
Screen Shot 2020-05-29 at 11 45 57 AM

**Comment by bonicim** [comment]
Fixed the last commit because I squashed the wrong commit and got confused on which TravisCI dashboard I was testing.

Also rebased to take in latest changes from develop.

**Comment by craig8** [comment]
Over come by events

**Pull request closed without merging**
