### PR TITLE
Fix the deployment documentation for Linux

### PR DESCRIPTION
**Pull request by peter-nordquist**
This documentation uses pipes in a fair amount of places and it messes
with the way rst collapses the content

If there is a reason for the pipes just reject this request and let me know, I had started to normalize the pipes so they were every line and it shouldn't be too hard to get back to that.

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/742)

### CODE REVIEW

**Comment by craig8** [comment]
@schandrika please take a look at this and merge if that's the right thing to do :)

**Comment by jhaack** [comment]
This documentation was ported over from a github wiki and some was originally written for TRAC so feel free to make things work better for RST.

**Comment by schandrika** [comment]
This is good. The | were making formatting bad in rst. Removal of those makes generated readthedocs page well formatted. 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/742#-:-KRe5DJoC9kPjmCbv8BH:b-hx6ibm)*

**Comment by schandrika** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/742)*

**Comment by schandrika** [comment]
Sorry I missed the merge yesterday

**Pull request merged**
