### PR TITLE
Bacpypes 13 and 16 compatibility.

### PR DESCRIPTION
**Pull request by kmonson**
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1509%23issuecomment-334936452%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1509%23issuecomment-334977044%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1509%23issuecomment-334936452%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22I%20understand%20you%20all%20are%20having%20problems%2C%20but%20removing%20all%20of%20the%20abstraction%20and%20returning%20it%20to%20the%20single%20huge%20method%20it%20was%20is%20not%20going%20to%20make%20it%20any%20more%20maintainable.%20Also%20I%20agree%20that%20PEP8%20is%20a%20bit%20draconian%20in%20its%20tradeoffs%20of%20standardization%20vs%20readability%2C%20but%20carte%20blanch%20ignoring%20of%20PEP8%20doesn%27t%20get%20you%20anywhere%20without%20adopting%20some%20other%20standard.%20This%20should%20be%20a%20testing%20branch%2C%20not%20a%20pull%20request.%22%2C%20%22created_at%22%3A%20%222017-10-07T13%3A50%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/977415%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/acedrew%22%7D%7D%2C%20%7B%22body%22%3A%20%22Sorry%20Andrew.%20I%20didn%27t%20have%20anything%20against%20your%20changes%20but%20I%20had%20to%20be%20absolutely%20sure%20they%20weren%27t%20causing%20the%20problem%20we%20were%20seeing.%20I%20wanted%20to%20reduce%20the%20changes%20to%20just%20what%20was%20needed%20to%20move%20past%200.13.8%2C%20then%20I%20could%20be%20sure%20it%20was%20a%20problem%20with%20bacpypes%20and%20not%20your%20changes.%20Right%20now%20we%20are%20under%20a%20time%20crunch%20to%20get%205.0%20out%20the%20door.%20This%20is%20a%20stopgap%20until%20Joel%20releases%20bacpypes%200.16.4%20which%20fixes%20the%20problem%20we%20are%20seeing.%5Cr%5Cn%5Cr%5CnAfter%20reviewing%20your%20code%20I%20did%20find%20one%20place%20where%20it%20was%20not%20equivalent%20in%20the%20error%20handling.%20I%20haven%27t%20had%20time%20to%20investigate%20if%20this%20would%20cause%20a%20problem.%20%28After%20further%20review%20probably%20not%2C%20but%20I%20don%27t%20have%20time%20to%20be%20sure.%29%5Cr%5Cn%5Cr%5CnI%20agree%20that%20it%20does%20need%20to%20be%20cleaned%20up.%20If%20I%20have%20time%20before%20the%20release%20I%27ll%20see%20if%20I%20can%20get%20your%20changes%20back%20in.%22%2C%20%22created_at%22%3A%20%222017-10-08T01%3A44%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/2049915%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kmonson%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/VOLTTRON/volttron/pull/1509#issuecomment-334936452'>General Comment</a></b>
- <a href='https://github.com/acedrew'></a> I understand you all are having problems, but removing all of the abstraction and returning it to the single huge method it was is not going to make it any more maintainable. Also I agree that PEP8 is a bit draconian in its tradeoffs of standardization vs readability, but carte blanch ignoring of PEP8 doesn't get you anywhere without adopting some other standard. This should be a testing branch, not a pull request.
- <a href='https://github.com/kmonson'></a> Sorry Andrew. I didn't have anything against your changes but I had to be absolutely sure they weren't causing the problem we were seeing. I wanted to reduce the changes to just what was needed to move past 0.13.8, then I could be sure it was a problem with bacpypes and not your changes. Right now we are under a time crunch to get 5.0 out the door. This is a stopgap until Joel releases bacpypes 0.16.4 which fixes the problem we are seeing.
After reviewing your code I did find one place where it was not equivalent in the error handling. I haven't had time to investigate if this would cause a problem. (After further review probably not, but I don't have time to be sure.)
I agree that it does need to be cleaned up. If I have time before the release I'll see if I can get your changes back in.

<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1509?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1509?approve=1'></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1509'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by craig8** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/VOLTTRON/volttron/pull/1509'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by acedrew** [comment]
I understand you all are having problems, but removing all of the abstraction and returning it to the single huge method it was is not going to make it any more maintainable. Also I agree that PEP8 is a bit draconian in its tradeoffs of standardization vs readability, but carte blanch ignoring of PEP8 doesn't get you anywhere without adopting some other standard. This should be a testing branch, not a pull request.

**Comment by kmonson** [comment]
Sorry Andrew. I didn't have anything against your changes but I had to be absolutely sure they weren't causing the problem we were seeing. I wanted to reduce the changes to just what was needed to move past 0.13.8, then I could be sure it was a problem with bacpypes and not your changes. Right now we are under a time crunch to get 5.0 out the door. This is a stopgap until Joel releases bacpypes 0.16.4 which fixes the problem we are seeing.

After reviewing your code I did find one place where it was not equivalent in the error handling. I haven't had time to investigate if this would cause a problem. (After further review probably not, but I don't have time to be sure.)

I agree that it does need to be cleaned up. If I have time before the release I'll see if I can get your changes back in.

**Comment by kmonson** [comment]
We are testing Andrew's version against bacpypes 0.16.4.

**Pull request closed without merging**
