### PR TITLE
Web refactor to support custom headers, binary data, and status codes

### PR DESCRIPTION
**Pull request by acedrew**
This is an example implementation of these features added in a backwards compatible way with agents using the JSON-RPC interface.

This addresses #1378, #1379, #1382, #1367 

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/1388)

### CODE REVIEW

**Comment by craig8** [comment]
Looks like you Brooke some tests

**Comment by acedrew** [comment]
working through the tests now

**Comment by sheridaj** [comment]
in create_raw_response in web.py, if res is a tuple of length 1 or 2, the call to start_response will crash because headers are not defined.

**Comment by acedrew** [comment]
Haha, yeah I forgot to go back and fillin/handle default values... That can
be easily resolved but I think @craig8 preferred we build an actual
response object with the appropriate helper functions, which is shown in
skeleton form

**Comment by acedrew** [comment]
@sheridaj is this functional? Obviously we're supposed to provide a content-type header, but I wasn't sure what would be the appropriate one to default to. I also don't think it's appropriate for the create_raw_response method to implement any mime detection or other higher level features, those should be built on top of this method.

**Pull request merged**
