### PR TITLE
Feature/key format cleanup

### PR DESCRIPTION
**Pull request by zbeech**
- Use replace use of curve.key file with KeyStore
- Changed KeyStore file permission from 0660 to 0600
- KeyStore returns str (not unicode) encoded keys (base64 decode needs str)
- Ran `autopep8` on modified files

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/525)

### CODE REVIEW

**Comment by craig8** [comment]
Is there a section in confluence about all the work you are doing with keystores?

**Comment by zbeech** [comment]
I haven't recording anything in confluence. Is there a particular confluence page or section I should update?

**Comment by craig8** [comment]
Not confluence…readthedocs

Pick a spot in the docs/source directory.  I would guess under agent development??

http://volttron.readthedocs.org

Craig

**Comment by zbeech** [comment]
I'll add a key-store section to readthedocs, and tie into the Authentication/Authorization section somehow.

**Comment by craig8** [comment]
Reviewed 2 of 7 files at r1.
Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[volttron/platform/keystore.py, line 123 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/525#-KHfr1gGHCtkklr872QT:-KHfr1gGHCtkklr872QU:-181557315) ([raw file](https://github.com/volttron/volttron/blob/4aa5a707b153f58a6b31c9ac117368fd9be44c7b/volttron/platform/keystore.py#L123)):*
> ```Python
>     def _get_key(self, keyname):
>         """Get key and make sure it is str (not unicode)
> ```

Hmmm how are you making sure it's not unicode.  I don't believe that str does transitions between unicode and non unicode characters?  

See http://stackoverflow.com/questions/1207457/convert-a-unicode-string-to-a-string-in-python-containing-extra-symbols

and

http://stackoverflow.com/questions/13980906/trouble-converting-a-string-from-unicode-in-python-2-7

---

*[volttrontesting/platform/keystore_test.py, line 27 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/525#-KHftEPyw0nHgS4ltBI4:-KHftEPyw0nHgS4ltBI5:-1263829363) ([raw file](https://github.com/volttron/volttron/blob/4aa5a707b153f58a6b31c9ac117368fd9be44c7b/volttrontesting/platform/keystore_test.py#L27)):*
> ```Python
>     assert os.stat(kspath).st_mode & 0o777 == 0o600
>     assert ks.secret()
>     assert ks.public()
> ```

Probably should add a test with some unicode characters to see what happens.

---

*[volttrontesting/utils/platformwrapper.py, line 176 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/525#-KHftQQCvxKtVme_yoJ2:-KHftQQCvxKtVme_yoJ3:-1021970023) ([raw file](https://github.com/volttron/volttron/blob/4aa5a707b153f58a6b31c9ac117368fd9be44c7b/volttrontesting/utils/platformwrapper.py#L176)):*
> ```Python
> 
>     def build_agent(self, address=None, should_spawn=True, identity=None,
>                     publickey=None, secretkey=None, serverkey=None, **kwargs):
> ```

Should this now be using the agent/utils.py file instead here?

---

*[volttrontesting/utils/platformwrapper.py, line 413 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/525#-KHftv_fZLNOvSiih9BM:-KHftv_fZLNOvSiih9BN:-235377219) ([raw file](https://github.com/volttron/volttron/blob/110639fc4bb866310ea46f815bfa0ad9e6b6833c/volttrontesting/utils/platformwrapper.py#L413)):*
> ```Python
>     #     pub.send_multipart([topic, data])
> 
>     # def fillout_file(self, filename, template, config_file):
> ```

This function probably should be dusted off and made into a useful function for defining config files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/525)*

**Comment by craig8** [comment]
The tiein to authentication/authorization sounds good.

**Comment by craig8** [comment]
The tiein with keystore and auth sounds like a good plan.

**Comment by zbeech** [comment]
*[volttron/platform/keystore.py, line 123 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/525#-KHfr1gGHCtkklr872QT:-KHfuh4U4jPb4XFoHudl:-1791268430) ([raw file](https://github.com/volttron/volttron/blob/4aa5a707b153f58a6b31c9ac117368fd9be44c7b/volttron/platform/keystore.py#L123)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> Hmmm how are you making sure it's not unicode.  I don't believe that str does transitions between unicode and non unicode characters?  
> 
> See http://stackoverflow.com/questions/1207457/convert-a-unicode-string-to-a-string-in-python-containing-extra-symbols
> 
> and
> 
> http://stackoverflow.com/questions/13980906/trouble-converting-a-string-from-unicode-in-python-2-7</details>
You're right. I probably need to reword the method comments to be more accurate. I'm not trying to convert an arbitrary Unicode string into an ASCII string; I just need to change the string's type from unicode to str. This is fine as long as the string only contains ASCII characters, which is guaranteed for valid encoded CURVE keys. 

The problem is that python's json module returns values of type unicode for all strings, even if they are composed entirely of ASCII characters. This made the encoded CURVE keys unicode, which could not be decoded because base64.urlsafe_b64decode expects str type. That's why we had to use that build_vip_address_string method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/525)*

**Comment by zbeech** [comment]
*[volttrontesting/utils/platformwrapper.py, line 176 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/525#-KHftQQCvxKtVme_yoJ2:-KHfzMWD-eYZgyV04zMC:72594621) ([raw file](https://github.com/volttron/volttron/blob/4aa5a707b153f58a6b31c9ac117368fd9be44c7b/volttrontesting/utils/platformwrapper.py#L176)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> Should this now be using the agent/utils.py file instead here?</details>
Maybe we should use the build_agent from agent/utils.py. This method does a few extra things that are specific for testing (automatically adds public key to auth file, takes a bool to determine if the agent should be spawned, etc). I think Chandrika is working on a branch that simplifies some of the unit test scaffolding regarding encryption. Maybe we can revisit this once that branch is merged into develop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/525)*

**Comment by zbeech** [comment]
It looks like the Authentication and Authorization documentation needs to be cleaned up, so I will do all of that in a separate branch.

**Comment by craig8** [comment]
Reviewed 2 of 7 files at r1, 1 of 1 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/525)*

**Comment by zbeech** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[volttrontesting/platform/keystore_test.py, line 27 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/525#-KHftEPyw0nHgS4ltBI4:-KHuVZlvWos3y54hjLc6:-499146009) ([raw file](https://github.com/volttron/volttron/blob/4aa5a707b153f58a6b31c9ac117368fd9be44c7b/volttrontesting/platform/keystore_test.py#L27)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> Probably should add a test with some unicode characters to see what happens.</details>
Done.

---

*[volttrontesting/utils/platformwrapper.py, line 413 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/525#-KHftv_fZLNOvSiih9BM:-KHuVgs5Pwf44HZH6RAB:-1888621083) ([raw file](https://github.com/volttron/volttron/blob/110639fc4bb866310ea46f815bfa0ad9e6b6833c/volttrontesting/utils/platformwrapper.py#L413)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> This function probably should be dusted off and made into a useful function for defining config files.</details>
Maybe we should address this in a different branch. I'm not sure how we want to use this fillout_file method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/525)*

**Comment by craig8** [comment]
@zbeech did we finish all of these up?

**Comment by zbeech** [comment]
@craig8 yes, everything for this branch is finished.

**Comment by craig8** [comment]
Reviewed 1 of 7 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/525)*

**Pull request merged**
