### PR TITLE
Feature/device revert

### PR DESCRIPTION
**Pull request by kmonson**
This change is [Review on Reviewable](https://reviewable.io/reviews/volttron/volttron/387)

### CODE REVIEW

**Comment by kmonson** [comment]
The one travis CI test that is failing is from auth.

**Comment by kmonson** [comment]
Closes #309

**Comment by craig8** [comment]
Reviewed 15 of 15 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/volttron/volttron/387)*

**Comment by craig8** [comment]
The failures in tests are due to the auth branch...They are fixed in a different branch

**Pull request merged**
