### PR TITLE
Add clarification on comments for 'database' parameter in sqlite historian config

### LINKED ISSUE #2526: Historian agent fails to build when database is an empty string
### Description of Issue
When an historian agent is installed with no directory given, i.e. database = "", the historian agent is not successfully installed because "database" must be specified (i.e. an empty string is considered an error). 

### Internal Issue Number
 jira_264

### Affected Version
8.0, using develop branch
### Screenshots
```
# volttron.log
    raise ConnectionError(e).with_traceback(sys.exc_info()[2])
  File "/home/mark2/Workplace/volttron/volttron/platform/dbutils/basedb.py", line 121, in cursor
    self.__connection = self.__connect()
  File "/home/mark2/Workplace/volttron/volttron/platform/dbutils/basedb.py", line 95, in <lambda>
    connect = lambda: dbapimodule.connect(**kwargs)
volttron.platform.dbutils.basedb.ConnectionError: unable to open database file

2020-11-06 17:32:59,667 (sqlhistorianagent-3.7.0 3327) volttron.platform.agent.base_historian DEBUG: Queue wait timed out. Falling out.
2020-11-06 17:32:59,667 (sqlhistorianagent-3.7.0 3327) volttron.platform.agent.base_historian INFO: Trying to setup historian
2020-11-06 17:32:59,667 (sqlhistorianagent-3.7.0 3327) __main__ DEBUG: historian_setup on Thread: Thread-1

# vctl status
AGENT                    IDENTITY                   TAG AGENT_USER                STATUS          HEALTH                                             
4 sqlhistorianagent-3.7.0  sqlhistorianagent-3.7.0_2      volttron_1604681860230849 running [3327]  BAD                  
```
#### Expected
Historian created and health shows as GOOD

#### Actual
Historian created and health shows as BAD

### Steps to Reproduce
1. Start Volttron platform
2. Modify services/core/SQLHistorian/config.sqlite by setting "database" set to an empty string
```
{
    "connection": {
        "type": "sqlite",
        "params": {
            # if no directory is given, location will be under install_dir/<agent name>.agent-data directory
            # in secure mode as this will be only directory in which agent will have write access
            # In regular mode it will be under install_dir/data for backward compatibility
            # "database": "historian_test.sqlite"
            "database": ""
        }
    },
    "all_platforms":true
}
```
3. Install historian 
```
$ python scripts/install-agent.py -s services/core/SQLHistorian/ -c services/core/SQLHistorian/config.sqlite
```

### PR DESCRIPTION
**Pull request by bonicim**
# Description

Fixes #2526 

Adds clarification on 'database' parameter that it should be a non-empty string, gives two examples, and revises the statements regarding the location of the database in secure vs regular mode. 

I tested creating a sqlite historian with an empty string for 'database' parameter and verified that no connection could be made since a location was not given:

```
# Configuration given to sqlite
{
    "connection": {
      "type": "sqlite",
      "params": {
        "database": ""
      }
    }
}

# Logs
20-12-04 22:09:46,842 (sqlhistorianagent-3.7.0 109) volttron.platform.dbutils.basedb DEBUG: kwargs for connect is {'database': '/home/volttron/.volttron/agents/6272c40a-5e5a-40c4-910d-5423772a2f73/sqlhistorianagent-3.7.0/sqlhistorianagent-3.7.0.agent-data/', 'detect_types': 3, 'timeout': 10}
2020-12-04 22:09:46,842 (sqlhistorianagent-3.7.0 109) volttron.platform.agent.base_historian DEBUG:

2020-12-04 22:09:46,871 (sqlhistorianagent-3.7.0 109) volttron.platform.dbutils.basedb ERROR: Could not connect to database. Raise ConnectionError
2020-12-04 22:09:46,871 (sqlhistorianagent-3.7.0 109) volttron.platform.agent.base_historian ERROR: Failed to setup historian!
Traceback (most recent call last):
  File "/code/volttron/volttron/platform/dbutils/basedb.py", line 121, in cursor
    self.__connection = self.__connect()
  File "/code/volttron/volttron/platform/dbutils/basedb.py", line 95, in <lambda>
    connect = lambda: dbapimodule.connect(**kwargs)
sqlite3.OperationalError: unable to open database file

```

## Type of change

Please delete options that are not relevant.

- [x] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by schandrika** [comment]
Ideally we want all these explanation to go into README. If README has all possible configuration values and explanations then config file can simply be an example.

**Comment by bonicim** [comment]
> Ideally we want all these explanation to go into README. If README has all possible configuration values and explanations then config file can simply be an example.

That makes sense. The current documentation for SQLite3 configuration has some typos anyways and I can put the explanation of the secure vs non-secure mode in the documentation.

**Comment by bonicim** [comment]
Moved comments to the README of Historian. Also updated the readthedocs to maintain consistency between the Historian documentation and what is on the readthedocs for Historian.

**Comment by bonicim** [comment]
Below are screenshots of the updated documentation.

For README of Historian:
Screen Shot 2020-12-07 at 12 37 53 PM

For readthedocs:
Screen Shot 2020-12-07 at 12 31 21 PM

**Pull request merged**
