### PR TITLE
Fix BACPypes version issue

### PR DESCRIPTION
**Pull request by jhaack**
#1347 Undo changes to BACPypes version. Should be 13.8

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/1349)

### CODE REVIEW

**Comment by acedrew** [comment]
This is going to break the proxy, give me this evening to take a look at the scanner, I assume you mean the BACnet helper scripts? I think I know exactly what needs to change to support the newer BACnet version.

**Comment by acedrew** [comment]
*BACpypes version.

**Comment by jhaack** [comment]
Ok, drop a note to @kmonson  when it's ready and he can take a look. Thanks

**Comment by jhaack** [comment]
@acedrew Are you still working on the fix for this? We got another pull request for it.

**Pull request closed without merging**
