### PR TITLE
Iterable schedule

### LINKED ISSUE #1823: [Feature Request] Schedule agent functions with cron like schedules
When building an agent it would be awesome to schedule agent functions with cron like schedules.

Example:
```
@Core.cron('0 1 * * *')
def foo(self):
    ...

```

### PR DESCRIPTION
**Pull request by hashstat**
# Description

Adds the ability to pass iterable objects to the core schedule decorator and associated method (dualmethod) as the deadline parameter. The iterable should yield datetime objects in increasing order and the scheduled function will be executed at the first time and automatically rescheduled at each execution, using the next time in the iterator. A new periodic() generator is added to use with the updated schedule functions, obsoleting the periodic decorator and associated method, which are now marked as deprecated.

Fixes #1823 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

Functionality was tested using a simple agent that schedules simple tasks using cron.schedule() and periodic() generators. The full suite of CI tests was also successfully run.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/VOLTTRON/volttron/pull/1827%23issuecomment-431985364%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1827%23issuecomment-432335949%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1827%23issuecomment-432354563%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1827%23issuecomment-432444710%22%2C%20%22https%3A//github.com/VOLTTRON/volttron/pull/1827%23issuecomment-432457805%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/VOLTTRON/volttron/pull/1827%23issuecomment-431985364%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%40hashstat%20This%20is%20good%20stuff.%20I%27m%20already%20thinking%20of%20ways%20to%20use%20this%20to%20clean%20up%20the%20master%20driver%20and%20actuator.%5Cr%5Cn%5Cr%5CnIf%20no%20one%20is%20using%20cron%20we%20should%20take%20advantage%20of%20this%20opportunity%20to%20move%20it%20to%20vip.agent.%20We%20are%20dropping%20support%20%20for%20pre%20VOLTTRON%203%20agents.%20Most%20of%20those%20imports%20remain%20in%20volttron.platform.agent%20due%20to%20momentum.%20Eventually%20we%27ll%20move%20them%20all%20out%20and%20put%20links%20to%20new%20vip.agent%20imports%20with%20a%20warning.%5Cr%5Cn%5Cr%5CnI%27ll%20let%20you%20decide%20if%20you%20want%20to%20bother%20with%20that%20and%20then%20I%27ll%20pull%20this%20in.%20%5Cr%5Cn%5Cr%5CnAlso%2C%20the%20tests%20aren%27t%20running...%20I%27ll%20have%20to%20figure%20that%20one%20out.%22%2C%20%22created_at%22%3A%20%222018-10-22T21%3A03%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/2049915%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kmonson%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40kmonson%20said%3A%5Cr%5Cn%3E%20If%20no%20one%20is%20using%20cron%20we%20should%20take%20advantage%20of%20this%20opportunity%20to%20move%20it%20to%20vip.agent.%5Cr%5Cn%5Cr%5Cn%40dmossie%20is%20the%20only%20person%20I%20know%20using%20cron%2C%20and%20just%20recently.%20I%20don%27t%20think%20he%20would%20object%20to%20moving%20the%20module.%5Cr%5Cn%5Cr%5CnPerhaps%20we%20should%20move%20cron%20to%20volttron.platform.scheduling%2C%20renaming%20schedule%28%29%20to%20cron%28%29%2C%20and%20then%20move%20periodic%28%29%20from%20vip.core%20into%20scheduling.%20These%20are%2C%20after%20all%2C%20just%20datetime%20generators%20and%20not%20vip-specific.%22%2C%20%22created_at%22%3A%20%222018-10-23T17%3A10%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1288789%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/hashstat%22%7D%7D%2C%20%7B%22body%22%3A%20%22This%20is%20true.%20Go%20for%20it.%20Just%20make%20sure%20you%20don%27t%20break%20backwards%20compatibility%20for%20everyone%20else.%22%2C%20%22created_at%22%3A%20%222018-10-23T17%3A59%3A46Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/2049915%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/kmonson%22%7D%7D%2C%20%7B%22body%22%3A%20%22%40kmonson%20Changes%20are%20in.%20This%20should%20be%20completely%20backward%20compatible.%20I%20even%20left%20a%20cron%20module%20in%20the%20original%20location%2C%20but%20marked%20it%20deprecated.%22%2C%20%22created_at%22%3A%20%222018-10-23T22%3A28%3A01Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/1288789%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/hashstat%22%7D%7D%2C%20%7B%22body%22%3A%20%22I%20think%20doing%20this%20is%20a%20great%20idea.%20My%20agent%20is%20using%20cron%20but%20I%20am%20happy%20to%20move%20it%20to%20this%20new%20functionality%20once%20it%20is%20finalized%20and%20available.%20Thanks%20guys%21%22%2C%20%22created_at%22%3A%20%222018-10-23T23%3A29%3A41Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/30665550%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/dmossie%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>
- [ ] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/VOLTTRON/volttron/pull/1827#issuecomment-431985364'>General Comment</a></b>
- <a href='https://github.com/kmonson'></a> @hashstat This is good stuff. I'm already thinking of ways to use this to clean up the master driver and actuator.
If no one is using cron we should take advantage of this opportunity to move it to vip.agent. We are dropping support  for pre VOLTTRON 3 agents. Most of those imports remain in volttron.platform.agent due to momentum. Eventually we'll move them all out and put links to new vip.agent imports with a warning.
I'll let you decide if you want to bother with that and then I'll pull this in.
Also, the tests aren't running... I'll have to figure that one out.
- <a href='https://github.com/hashstat'></a> @kmonson said:
> If no one is using cron we should take advantage of this opportunity to move it to vip.agent.
@dmossie is the only person I know using cron, and just recently. I don't think he would object to moving the module.
Perhaps we should move cron to volttron.platform.scheduling, renaming schedule() to cron(), and then move periodic() from vip.core into scheduling. These are, after all, just datetime generators and not vip-specific.
- <a href='https://github.com/kmonson'></a> This is true. Go for it. Just make sure you don't break backwards compatibility for everyone else.
- <a href='https://github.com/hashstat'></a> @kmonson Changes are in. This should be completely backward compatible. I even left a cron module in the original location, but marked it deprecated.
- <a href='https://github.com/dmossie'></a> I think doing this is a great idea. My agent is using cron but I am happy to move it to this new functionality once it is finalized and available. Thanks guys!

<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1827?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/VOLTTRON/volttron/pull/1827?approve=1'></a>&nbsp;<a href='https://github.com/VOLTTRON/volttron/pull/1827'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by craig8** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/VOLTTRON/volttron/pull/1827'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by kmonson** [comment]
@hashstat This is good stuff. I'm already thinking of ways to use this to clean up the master driver and actuator.

If no one is using cron we should take advantage of this opportunity to move it to vip.agent. We are dropping support  for pre VOLTTRON 3 agents. Most of those imports remain in volttron.platform.agent due to momentum. Eventually we'll move them all out and put links to new vip.agent imports with a warning.

I'll let you decide if you want to bother with that and then I'll pull this in. 

Also, the tests aren't running... I'll have to figure that one out.

**Comment by hashstat** [comment]
@kmonson said:
> If no one is using cron we should take advantage of this opportunity to move it to vip.agent.

@dmossie is the only person I know using cron, and just recently. I don't think he would object to moving the module.

Perhaps we should move cron to volttron.platform.scheduling, renaming schedule() to cron(), and then move periodic() from vip.core into scheduling. These are, after all, just datetime generators and not vip-specific.

**Comment by kmonson** [comment]
This is true. Go for it. Just make sure you don't break backwards compatibility for everyone else.

**Comment by hashstat** [comment]
@kmonson Changes are in. This should be completely backward compatible. I even left a cron module in the original location, but marked it deprecated.

**Comment by dmossie** [comment]
I think doing this is a great idea. My agent is using cron but I am happy to move it to this new functionality once it is finalized and available. Thanks guys!

**Pull request merged**
