### PR TITLE
rearrange vc demo doc for clarity #987

### PR DESCRIPTION
**Pull request by mikeroup**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/990)

### CODE REVIEW

**Comment by craig8** [comment]
@jchap-pnnl please review

**Comment by jchap-pnnl** [comment]
The reorganization looks good. The content makes sense. There were just a couple of commas that could be inserted.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst, line 97 at r1](https://reviewable.io:443/reviews/volttron/volttron/990#-KV5vRNfpsB5keGAeyH-:-KV5vRNgEUL0da2jRhNQ:bz40izs) ([raw file](https://github.com/volttron/volttron/blob/3ce7bb4e74d5c1752e5b8afe7a85aadc1a113c13/docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst#L97)):*
> ```reStructuredText
> The next step is to configure the instances that will connect to VOLTTRON
> Central. In the second and third terminal windows run `volttron-cfg`. Like
> the VOLTTRON\_HOME variable these instances need to have unique addresses.
> ```

Should insert a comma after variable: Like the VOLTTRON\_HOME variable, these instances ...

---

*[docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst, line 100 at r1](https://reviewable.io:443/reviews/volttron/volttron/990#-KV5vfjHQHweu2nrrzgv:-KV5vfjIS6MXa6-3kb4K:b1lt9jc) ([raw file](https://github.com/volttron/volttron/blob/3ce7bb4e74d5c1752e5b8afe7a85aadc1a113c13/docs/source/devguides/walkthroughs/VOLTTRON-Central-Demo.rst#L100)):*
> ```reStructuredText
> 
> Install a platform agent and a historian as before. Since we used the default
> options when configuring VOLTTRON Central we can use the default options when
> ```

Should insert a comma after Central: Since we used the default options when configuring VOLTTRON Central, we can use ...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/990#-:-KV5w03upAyFc_C5BDyc:b-h708yy)*

**Comment by jchap-pnnl** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/990#-:-KV5xaYAYZU93fflpmhY:bnfp4nl)*

**Comment by jchap-pnnl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/990)*

**Pull request merged**
