### PR TITLE
Remove legacy class definitions

### PR DESCRIPTION
**Pull request by Siecje**

### CODE REVIEW

**Comment by craig8** [comment]
@Siecje can you tell me about the modifications to the js file for this pr?

**Review by craig8 — APPROVED** [review]

**Comment by Siecje** [comment]
I'm interested, I just emailed the mailing list.

**Comment by craig8** [comment]
Great and thanks for the clean up that you have been doing.

**Comment by craig8** [comment]
@Siecje  https://www.eclipse.org/legal/ECA.php please sign the eclipse agreement if you haven't...I forgot to mention this on earlier PRs as I was excited by the pull requests.

**Comment by Siecje** [comment]
Signed.

**Pull request merged**
