### PR TITLE
fix channel race condition at agent start-up

### PR DESCRIPTION
**Pull request by mikeroup**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/698)

### CODE REVIEW

**Comment by craig8** [comment]
@kmonson would you please look through this and let me know your thoughts?

**Comment by kmonson** [comment]
I reviewed this in person right before he made the pull request. It looks good to me.

**Comment by mikeroup** [comment]
Everything is broken.

**Comment by craig8** [comment]
@mikeroup it seems that all of the tests are now ERROR ing out if they aren't skipped.  Please check this out.

**Comment by craig8** [comment]
Why'd you break it :)

**Pull request closed without merging**
