### PR TITLE
Fixes #811

### LINKED ISSUE #811: Identity not being picked up from configuration file
"identity" is not being used in old style configuration files (such as platform.historian). 

This will cause confusion with deployments not done through volttron-cfg.

Either pick identity up out of old configuration files or highlight this breaking change.

### PR DESCRIPTION
**Pull request by kmonson**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/818)

### CODE REVIEW

**Comment by craig8** [comment]
This does not seem to work
````
volttron)vdev@vdev-VirtualBox ~/git/volttron-upstream $ volttron-ctl status
  AGENT                       IDENTITY                      TAG                STATUS
2 filewatchpublisheragent-0.1 platform.filewatchpublisher1
 filepub                  
6 listeneragent-3.2           listeneragent-3.2_1           listener                 
e sqlhistorianagent-3.5.0     sqlhistorianagent-3.5.0_1     platform-historian running [1040]
````
I used this script to test it out.  Assumes you are in the root of the volttron directory.

````
export CONFIG=/tmp/sqlite.config

cat >$CONFIG <<EOL
{
  "agentid": "sqlhistorian-sqlite",
  "identity": "platform.historian",
    "connection": {
    "type": "sqlite",
    "params": {
      "database": "~/.volttron/data/platform.historian.sqlite"
    }
  }
}

EOL

export SOURCE=services/core/SQLHistorian
export TAG=platform-historian

# Uncomment this to set the identity of the agent. Overrides the platform default identity and the agent's
# preferred identity.
#export AGENT_VIP_IDENTITY=my_listener

./scripts/core/make-agent.sh 
````

**Comment by kmonson** [comment]
What are you expecting?

If you are expecting the output of 

    volttron-ctl status 

to match what you have in your configuration file that will never work. 

The status command looks at the identity file one disk which is not changed by this hack. The hack ignores the platform value and overrides it with the value of the configuration. The status command has no way of knowing what is going on.

**Comment by craig8** [comment]
Ahhh that is what I was expecting

**Comment by kmonson** [comment]
I spoke with @jhaack about this. 

We are going to put a deprecation warning in these historians if the user tries to supply an identity in their configuration along with instructions on how to do it right.

We'll also add "make historian" scripts to go along with the make listener script.

**Comment by kmonson** [comment]
@craig8 I did point this out yesterday.

https://github.com/VOLTTRON/volttron/issues/811#issuecomment-251785879

**Comment by craig8** [comment]
@kmonson can you fix the conflict please

**Comment by kmonson** [comment]
There you go.

**Pull request merged**
