### PR TITLE
Feature/alert

### PR DESCRIPTION
**Pull request by craig8**
Ignore the fact that this was started as an email branch.

The code I want you to look at is the status and alert code.  I have refactored it so that I think it is clearer.

@mikeroup

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/444)

### CODE REVIEW

**Comment by mikeroup** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[services/core/EmailerAgent/emailer/agent.py, line 202 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/444#-KEXqvzgIhxOPuv1m8HC:-KEXqvzgIhxOPuv1m8HD:1934969791) ([raw file](https://github.com/volttron/volttron/blob/becda255dfe433f05dc24b503f18275461ba64f2/services/core/EmailerAgent/emailer/agent.py#L202)):*
Code that is commented out might as well be removed.

---

*[volttron/platform/messaging/health.py, line 26 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/444#-KEXsdcdx1SEePq53gaF:-KEXsdcenYaUewkyKysZ:-742323901) ([raw file](https://github.com/volttron/volttron/blob/becda255dfe433f05dc24b503f18275461ba64f2/volttron/platform/messaging/health.py#L26)):*
Typos: methodss and object's

---

*[volttron/platform/messaging/topics.py, line 103 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/444#-KEXtIjPxY5ZV0NjSjP9:-KEXtIjQewfpP_JC9NLp:-2022675895) ([raw file](https://github.com/volttron/volttron/blob/becda255dfe433f05dc24b503f18275461ba64f2/volttron/platform/messaging/topics.py#L103)):*
What is this for/where is it used?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/444)*

**Comment by mikeroup** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[volttron/platform/messaging/health.py, line 36 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/444#-KEXzWFROjM3zQ8Dlcey:-KEXy4wQW5Jfe7qCCj3g:1746217496) ([raw file](https://github.com/volttron/volttron/blob/becda255dfe433f05dc24b503f18275461ba64f2/volttron/platform/messaging/health.py#L36)):*
Could _last_updated be initialized to none?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/444)*

**Comment by craig8** [comment]
Review status: 8 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[services/core/EmailerAgent/emailer/agent.py, line 202 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/444#-KEXqvzgIhxOPuv1m8HC:-KEXzfF1MTfznLHLTNmJ:-1292953068) ([raw file](https://github.com/volttron/volttron/blob/becda255dfe433f05dc24b503f18275461ba64f2/services/core/EmailerAgent/emailer/agent.py#L202)):*
For sure...that's why I said not to look into this part of the code :)

---

*[volttron/platform/messaging/health.py, line 26 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/444#-KEXsdcdx1SEePq53gaF:-KEY-WUH4xYk32SOHXb9:-499146009) ([raw file](https://github.com/volttron/volttron/blob/becda255dfe433f05dc24b503f18275461ba64f2/volttron/platform/messaging/health.py#L26)):*
Done.

---

*[volttron/platform/messaging/health.py, line 36 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/444#-KEXzWFROjM3zQ8Dlcey:-KEY-teML1QEEbArL9jd:1648607759) ([raw file](https://github.com/volttron/volttron/blob/becda255dfe433f05dc24b503f18275461ba64f2/volttron/platform/messaging/health.py#L36)):*
No, because _status has a value.  

If the user instanciates the object 
  s = Status()

then calls from_json()
  and expects to get the last_updated timestamp they would get one that won't work.

Also since None is not a valid timestamp it could cause debugging headache.

So this signifies that the status has been set since a particular point.  The other issue would be if the user called from_json after constructing the value they could potentially get inconsistent results.

---

*[volttron/platform/messaging/topics.py, line 103 \[r1\]](https://reviewable.io:443/reviews/volttron/volttron/444#-KEXtIjPxY5ZV0NjSjP9:-KEY0vBlTwnob10sp2hV:-479018648) ([raw file](https://github.com/volttron/volttron/blob/becda255dfe433f05dc24b503f18275461ba64f2/volttron/platform/messaging/topics.py#L103)):*
This should be used in your heartbeat code as the root of all heartbeats.  I don't think that it is currently however.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/444)*

**Comment by mikeroup** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/444)*

**Pull request merged**
