### PR TITLE
Merge from Bugfix/chartsave back into releases/Rc1

### PR DESCRIPTION
**Pull request by jchap-pnnl**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/586)

### CODE REVIEW

**Comment by craig8** [comment]
Reviewed 1 of 29 files at r7.
Review status: 1 of 28 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[services/core/VolttronCentral/ui-src/js/action-creators/platform-action-creators.js, line 19 \[r7\]](https://reviewable.io:443/reviews/volttron/volttron/586#-KIeL19AkM4tJfUs_-6Q:-KIeL19BxHwZote_rDt0:-2110026364) ([raw file](https://github.com/volttron/volttron/blob/d7d332d49718607221c8d431cdab930d2629357b/services/core/VolttronCentral/ui-src/js/action-creators/platform-action-creators.js#L19)):*
> ```JavaScript
>         var authorization = authorizationStore.getAuthorization();
> 
>         console.log("loading agents for " + platform.name);
> ```

Do we want console logs in the results...I would assume yes, but thought I would check to make sure you meant it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/586)*

**Comment by jchap-pnnl** [comment]
No, I meant to remove that.

**Comment by craig8** [comment]
Reviewed 6 of 30 files at r1, 1 of 12 files at r3, 5 of 28 files at r5, 1 of 3 files at r6, 24 of 30 files at r7, 3 of 4 files at r8.
Review status: 24 of 28 files reviewed at latest revision, 4 unresolved discussions.

---

*[services/core/VolttronCentral/ui-src/js/components/navigation.jsx, line 25 \[r7\]](https://reviewable.io:443/reviews/volttron/volttron/586#-KIeMt7Pm7kZewgbTvM1:-KIeMt7Qrjo-NoOP3RBl:-611568886) ([raw file](https://github.com/volttron/volttron/blob/d7d332d49718607221c8d431cdab930d2629357b/services/core/VolttronCentral/ui-src/js/components/navigation.jsx#L25)):*
> ```JSX
>         // platformsPanelActionCreators.resetPanel();
>         platformManagerActionCreators.clearAuthorization();
>     },
> ```

Odd that 2 out of three here are commented out. 

---

*[services/core/VolttronCentral/ui-src/js/components/platform-chart.jsx, line 101 \[r7\]](https://reviewable.io:443/reviews/volttron/volttron/586#-KIeN5WPOvgUGmF8Ut29:-KIeN5WPOvgUGmF8Ut2A:1045225589) ([raw file](https://github.com/volttron/volttron/blob/d7d332d49718607221c8d431cdab930d2629357b/services/core/VolttronCentral/ui-src/js/components/platform-chart.jsx#L101)):*
> ```JSX
>         // platformChartActionCreators.removeChart(this.props.chartKey);
>         // platformActionCreators.saveCharts();
>     },
> ```

I assume that these were having stacked charts but has been moved elsewhere?

---

*[services/core/VolttronCentral/ui-src/js/components/platform-charts.jsx, line 4 \[r7\]](https://reviewable.io:443/reviews/volttron/volttron/586#-KIeNFThAiZ1aOTT1P3o:-KIeNFThAiZ1aOTT1P3p:-1614968799) ([raw file](https://github.com/volttron/volttron/blob/d7d332d49718607221c8d431cdab930d2629357b/services/core/VolttronCentral/ui-src/js/components/platform-charts.jsx#L4)):*
> ```JSX
> 
> var React = require('react');
> var PlatformChart = require('./platform-chart');
> ```

We aren't using react-router any longer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/586)*

**Comment by jchap-pnnl** [comment]
Review status: 24 of 28 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[services/core/VolttronCentral/ui-src/js/components/navigation.jsx, line 25 \[r7\]](https://reviewable.io:443/reviews/volttron/volttron/586#-KIeMt7Pm7kZewgbTvM1:-KIeRiMyK0p6EfEZ6aNo:-384995483) ([raw file](https://github.com/volttron/volttron/blob/d7d332d49718607221c8d431cdab930d2629357b/services/core/VolttronCentral/ui-src/js/components/navigation.jsx#L25)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> Odd that 2 out of three here are commented out. 
</details>
It just looks odd since I left the two commented out that are going away. Their actions were able to be combined under one handler in the store.

---

*[services/core/VolttronCentral/ui-src/js/components/platform-chart.jsx, line 101 \[r7\]](https://reviewable.io:443/reviews/volttron/volttron/586#-KIeN5WPOvgUGmF8Ut29:-KIeSv0gwYKnMAap6v5T:-1022583908) ([raw file](https://github.com/volttron/volttron/blob/d7d332d49718607221c8d431cdab930d2629357b/services/core/VolttronCentral/ui-src/js/components/platform-chart.jsx#L101)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> I assume that these were having stacked charts but has been moved elsewhere?
</details>
This commented-out part is what was being used while the Confirm Remove Chart modal dialog was temporarily commented out. Since hopefully the page-reload-on-modal-close issue is now fixed, we can go back to using the Confirm Remove Chart dialog. This part is still there, though, commented out in case the fix for modals actually doesn't work and we need to go back to just immediate removal of charts.

---

*[services/core/VolttronCentral/ui-src/js/components/platform-charts.jsx, line 4 \[r7\]](https://reviewable.io:443/reviews/volttron/volttron/586#-KIeNFThAiZ1aOTT1P3o:-KIeTYj3zHO85k5cbZwo:-1603886789) ([raw file](https://github.com/volttron/volttron/blob/d7d332d49718607221c8d431cdab930d2629357b/services/core/VolttronCentral/ui-src/js/components/platform-charts.jsx#L4)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> We aren't using react-router any longer?
</details>
We are still using react-router. It just doesn't need to be included here -- there's no references to it in platform-charts.jsx.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/586)*

**Comment by craig8** [comment]
Reviewed 1 of 30 files at r7.
Review status: 25 of 28 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/586)*

**Pull request merged**
