### PR TITLE
Refactor volttron-cfg

### PR DESCRIPTION
**Pull request by mikeroup**
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/735)

### CODE REVIEW

**Comment by craig8** [comment]
There is an error if the VOLTTRON_HOME does not exist.  To reproduce remove your ~/.volttron directory and execute thusly
```
(volttron)vdev@big-mint-cinn ~/git/volttron $ volttron-cfg

Your VOLTTRON_HOME currently set to: /home/vdev/.volttron

Is this the volttron you are attempting to setup?  [Y]: 
What is the external instance ipv4 address? [tcp://127.0.0.1]: 
What is the instance port for the vip address? [22916]: 
Traceback (most recent call last):
  File "/home/vdev/git/volttron/env/bin/volttron-cfg", line 9, in <module>
    load_entry_point('volttron', 'console_scripts', 'volttron-cfg')()
  File "/home/vdev/git/volttron/volttron/platform/config.py", line 607, in _main
    main()
  File "/home/vdev/git/volttron/volttron/platform/instance_setup.py", line 476, in main
    wizard()
  File "/home/vdev/git/volttron/volttron/platform/instance_setup.py", line 441, in wizard
    _install_config_file()
  File "/home/vdev/git/volttron/volttron/platform/instance_setup.py", line 102, in _install_config_file
    os.makedirs(volttron_home, 0o755)
NameError: global name 'volttron_home' is not defined
```

**Comment by jhaack** [comment]
Verified fix for missing volttron_home

**Comment by craig8** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/source/core_services/control/PlatformCommands.rst, line 132 at r3](https://reviewable.io:443/reviews/volttron/volttron/735#-KRdTu3GY2rA-hqH2-No:-KRdTu3GY2rA-hqH2-Np:b-a6ubxn) ([raw file](https://github.com/volttron/volttron/blob/9c2861aac0e7de6b228eae3099d43e9379f6a21b/docs/source/core_services/control/PlatformCommands.rst#L132)):*
> ```reStructuredText
>         verify              verify an agent package
> 
> volttron-cfg Commands
> ```

probably should lowercase commands here since you did above.

---

*[docs/source/core_services/control/PlatformCommands.rst, line 146 at r3](https://reviewable.io:443/reviews/volttron/volttron/735#-KRdU5OsdmFwqKt-yGG7:-KRdU5OsdmFwqKt-yGG8:b-3qz23o) ([raw file](https://github.com/volttron/volttron/blob/9c2861aac0e7de6b228eae3099d43e9379f6a21b/docs/source/core_services/control/PlatformCommands.rst#L146)):*
> ```reStructuredText
>     positional arguments:
>       agent       List of agents to configure ['vcp', 'vc', 'platform_historian']
> ```

Is there a way to get the list of agents without the --help option?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/735)*

**Comment by craig8** [comment]
Also in some of the function comments you removed a """ coment starts to make it """comment starts.  Please change the rest as well.

**Comment by mikeroup** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/source/core_services/control/PlatformCommands.rst, line 132 at r3](https://reviewable.io:443/reviews/volttron/volttron/735#-KRdTu3GY2rA-hqH2-No:-KRdeG1UocPMwfrghgd1:b-jw0ctf) ([raw file](https://github.com/volttron/volttron/blob/9c2861aac0e7de6b228eae3099d43e9379f6a21b/docs/source/core_services/control/PlatformCommands.rst#L132)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> probably should lowercase commands here since you did above.
</details>
All three sections in that page are formatted the same. Are you talking about line 97?

---

*[docs/source/core_services/control/PlatformCommands.rst, line 146 at r3](https://reviewable.io:443/reviews/volttron/volttron/735#-KRdU5OsdmFwqKt-yGG7:-KRdfDJwkkAwCUyzae-D:b-ysi4c8) ([raw file](https://github.com/volttron/volttron/blob/9c2861aac0e7de6b228eae3099d43e9379f6a21b/docs/source/core_services/control/PlatformCommands.rst#L146)):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> Is there a way to get the list of agents without the --help option?
</details>
Not currently but I could add one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/735)*

**Comment by craig8** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/source/core_services/control/PlatformCommands.rst, line 132 at r3](https://reviewable.io:443/reviews/volttron/volttron/735#-KRdTu3GY2rA-hqH2-No:-KRdgDYG2K4oyJCrFk0k:bg8cjwr) ([raw file](https://github.com/volttron/volttron/blob/9c2861aac0e7de6b228eae3099d43e9379f6a21b/docs/source/core_services/control/PlatformCommands.rst#L132)):*
<details><summary><i>Previously, mikeroup (Mike Roup) wrote…</i></summary>
> All three sections in that page are formatted the same. Are you talking about line 97?
</details>
My bad I read that you put all but one lowercase...turns out you put them all with an uppercase Command.  Ignore this comment.

---

*[docs/source/core_services/control/PlatformCommands.rst, line 146 at r3](https://reviewable.io:443/reviews/volttron/volttron/735#-KRdU5OsdmFwqKt-yGG7:-KRdgBUlppKw3VLm9L4n:bqlspte) ([raw file](https://github.com/volttron/volttron/blob/9c2861aac0e7de6b228eae3099d43e9379f6a21b/docs/source/core_services/control/PlatformCommands.rst#L146)):*
<details><summary><i>Previously, mikeroup (Mike Roup) wrote…</i></summary>
> Not currently but I could add one.
</details>
Please do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/735)*

**Pull request merged**
