### PR TITLE
Additional Endpoints for VUI API

### PR DESCRIPTION
**Pull request by davidraker**
# Description

Added:
* Platforms Agents Configs endpoints (configuration store management).

Fixes # (issue)
VOLTTRON/volttron-web-service/issues/11
VOLTTRON/volttron-web-service/issues/12
VOLTTRON/volttron-web-service/issues/13
VOLTTRON/volttron-web-service/issues/14
VOLTTRON/volttron-web-service/issues/15
VOLTTRON/volttron-web-service/issues/35

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Unit tests in volttrontesting/platform/web/test_vui_endpoints.py.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by craig8** [comment]
The agents end point only returns agents that are currently running on the platform.

```
http://localhost:8070/vui/platforms/volttron1 ==============================
DEBUG:volttron.web.client.base:============================== GET /vui/platforms/volttron1/agents ==============================
DEBUG:volttron.web.client.base:{'route_options': {'platform.driver': '/vui/platforms/volttron1/agents/platform.driver'}}
DEBUG:volttron.web.client.base:============================== END GET http://localhost:8070/vui/platforms/volttron1/agents ==============================
```

```
vctl list
  AGENT                    IDENTITY            TAG                   PRI
a listeneragent-3.3        listeneragent-3.3_1 listener
1 platform_driveragent-4.0 platform.driver     platform_driver
b sqlhistorianagent-4.0.0  platform.historian  platform_historian
```

**Comment by davidraker** [comment]
The default value of the sgent-state query parameter is "r unning". To see all installed agents, try:
GET /vui/platforms/volttron1/agents?agent-state=installed

**Comment by craig8** [comment]
beautiful.

**Comment by craig8** [comment]
Calling /vui/platforms/{self.name}/agents/{identity} with an identity that doesn't exist, returns a 200 and paths to links that shouldn't exist.

Should we instead do a 404 or 405? response code?

I thiink you have this as a pattern for config store entries...but this should be a different pattern.

**Comment by davidraker** [comment]
Yeah, if that's true, it's a bug. We need to check if the identity exists, and 404 it. Same should be true if config store entries don't exist,  actually. Only POST config should work if the entry doesn't exist.


-------- Original message --------
From: Craig ***@***.***>
Date: 5/20/22 18:31 (GMT-06:00)
To: VOLTTRON/volttron ***@***.***>
Cc: "Raker, David M" ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [VOLTTRON/volttron] Additional Endpoints for VUI API (PR #2948)


Calling /vui/platforms/{self.name}/agents/{identity} with an identity that doesn't exist, returns a 200 and paths to links that shouldn't exist.

Should we instead do a 404 or 405? response code?

I thiink you have this as a pattern for config store entries...but this should be a different pattern.

**Pull request merged**
