### PR TITLE
Implement MesaAgent-VUA 2.0

### PR DESCRIPTION
**Pull request by anhnguyen-cpi**
- Update AN2018 mesa_points.config and mesa_functions.yaml
   - Process data when MesaAgent receives a point that appears in multiple functions
   - Attach selector_block data when publishing a function with func_ref
   - Support publishing multiple curves in one function
   - Fix hanging on close_outstation
   - More regression tests and validations
   - DNP3Master: add send_read_command and send_unsolicited_response_command for future development
   - Not allowed to modify evariation and svariation
   - Update README and readthedocs

### CODE REVIEW

**Comment by craig8** [comment]
Thanks @anhnguyen-cpi we will get this into the develop branch as soon as we finalize the 6.0 code base and get that into develop!

**Comment by shwethanidd** [comment]
@anhnguyen-cpi Please ensure that tests worked on both zmq and rmq message bus.

**Comment by kmonson** [comment]
@craig8 @shwethanidd What is the ETA on this?

We need it for a project we are currently working on.

**Comment by shwethanidd** [comment]
@kmonson Some pytests were failing so we were hesitant to merge. Should be this week.

**Comment by craig8** [comment]
@anhnguyen-cpi Can you tell me if these failed tests are something that we don't have for the test environment or something that needs to be updated in the tests

[dnp3_tests.txt](https://github.com/VOLTTRON/volttron/files/3163485/dnp3_tests.txt)

**Pull request merged**
