### PR TITLE
Merge fixes for VC and VCP

### PR DESCRIPTION
**Pull request by craig8**
Improves registration of remote platforms.
Addresses alot of #661

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/676)

### CODE REVIEW

**Comment by craig8** [comment]
Reviewed 3 of 45 files at r1.
Review status: 3 of 42 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/676)*

**Comment by jhaack** [comment]
Reviewed 20 of 45 files at r1.
Review status: 22 of 42 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/volttron/volttron/676#-KNpDMhhYRcs3UW-r7rW:-KNpDMhhYRcs3UW-r7rX:-1424864900) (no related file):*
Started up platform after using volttron-cfg, got the following:

(volttron)volttron@volttron-VirtualBox ~/git/volttron $ None
None
None
None


If the user is required to enter http on the VC address, include that in the example prompt:
Address of the volttron central to connect to? [127.0.0.1]: 

Will this instance register with a volttron central? (either locally or remotely) [Y]: 
Is this instance a volttron central? [N]: 
Please enter the external ipv4 address for this instance? [127.0.0.1]: 

IP address for this instance
Is this a VC?
Will it register with a VC?
IP for VC
etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/676)*

**Comment by craig8** [comment]
Review status: 20 of 43 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/volttron/volttron/676#-KNpDMhhYRcs3UW-r7rW:-KO8iQaFWW3hIDqj2PIG:2023723447) (no related file):*
<details><summary><i>Previously, jhaack wrote…</i></summary>
> Started up platform after using volttron-cfg, got the following:
> 
> (volttron)volttron@volttron-VirtualBox ~/git/volttron $ None
> None
> None
> None
> 
> 
> If the user is required to enter http on the VC address, include that in the example prompt:
> Address of the volttron central to connect to? [127.0.0.1]: 
> 
> Will this instance register with a volttron central? (either locally or remotely) [Y]: 
> Is this instance a volttron central? [N]: 
> Please enter the external ipv4 address for this instance? [127.0.0.1]: 
> 
> IP address for this instance
> Is this a VC?
> Will it register with a VC?
> IP for VC
> etc.
> 
> 
> 
</details>
I have fixed the issues with the wording.  Hopefully it's better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/676)*

**Comment by jhaack** [comment]
Review status: 20 of 43 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/volttron/volttron/676#-KNpDMhhYRcs3UW-r7rW:-KO8wGaPcUdeAYbo6x4n:-1504900868) (no related file):*
<details><summary><i>Previously, craig8 (Craig) wrote…</i></summary>
> I have fixed the issues with the wording.  Hopefully it's better.
</details>
Install an agent through UI. 
Start agent
Stop button never enables
Encountered an issue where platform page did not respond after refreshing the browser once
Otherwise, refreshing the page or navigating to index then back to platform works and stop is enabled

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/676)*

**Comment by jhaack** [comment]
Review status: 20 of 43 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/volttron/volttron/676#-KNpDMhhYRcs3UW-r7rW:-KO8wx736lEqClje3i73:-536412321) (no related file):*
<details><summary><i>Previously, jhaack wrote…</i></summary>
> Install an agent through UI. 
> Start agent
> Stop button never enables
> Encountered an issue where platform page did not respond after refreshing the browser once
> Otherwise, refreshing the page or navigating to index then back to platform works and stop is enabled
> 
</details>
Also, after hitting Remove button, agent status turns to "starting" until it is removed and disappears from UI

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/676)*

**Comment by craig8** [comment]
Per @jhaack this merge is a go

**Pull request closed without merging**
