### PR TITLE
Add --all-tagged option; add and fix vctl tests

### LINKED ISSUE #2881: Add vctl feature to start, stop, restart all agents with tags
This is an internal issue tracked in an internal [Jira ticket](https://jira.pnnl.gov/jira/browse/VOLTDEV-467) accessible only to core team developers. Please see that ticket for details.

### PR DESCRIPTION
**Pull request by bonicim**
# Description

What is the change?

* Adds `--all-tagged` option
* Refactors start_agent, stop_agent
* Changes 'nargs' input for start, stop, restart commands
* Manually handle input validation for start, stop, and restart
* Adds tests for --all-tagged, --tag, and starting an agent by uuid 
* Adds try/except to connection tests to check if the error message is an empty string; 

Why is it needed?

* Gives users the ability to start, stop, restart only tagged agents
* Make start_agent and stop_agent more DRY
* The current contract of `vctl start`, `vctl stop`, and `vctl restart`  requires a positional argument; however, the `--all-tagged` does not require any input. Thus to maintain the current contract of the commands while supporting the `--all-tagged` option that doesn't require an input, the 'nargs' argument needs to change from '+' to '*'.  This change will no longer use the automatic input validation that '+' offers (see [Python docs](https://docs.python.org/3/library/argparse.html#nargs)). Thus, we need to manually handle input validation.  
* Ensures that control tests pass in CI pipeline; currently always failing, see https://github.com/VOLTTRON/volttron/actions/workflows/pytest-vctl.yml

 Fixes #2881 

## Type of change

- [x] New feature (non-breaking change which adds functionality)


# How Has This Been Tested?

See screen recording: https://youtu.be/nAYG6L7mKVU

Also, ran the control tests:

```shell
pytest volttrontesting/platform/control_tests/test_vctl_commands.py 

# Results
=== test session starts ==
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /home/bono/Workplace/volttron-project/volttron/env/bin/python
cachedir: .pytest_cache
rootdir: /home/bono/Workplace/volttron-project/volttron, configfile: pytest.ini
plugins: timeout-2.1.0, rerunfailures-10.2, asyncio-0.18.1
asyncio: mode=auto
collected 26 items                                                                                                                                                                                                                

volttrontesting/platform/control_tests/test_vctl_commands.py::test_needs_connection PASSED                                                                                                                                  [  3%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_needs_connection_with_connection[volttron_instance0] PASSED                                                                                              [  7%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_no_connection[volttron_instance0] PASSED                                                                                                                 [ 11%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_same_identity[volttron_instance0] PASSED                                                                                                         [ 15%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_with_wheel[volttron_instance0] PASSED                                                                                                            [ 19%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_with_wheel_bad_path[volttron_instance0] PASSED                                                                                                   [ 23%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-True-args0] PASSED                                                                                                 [ 26%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-True-args1] PASSED                                                                                                 [ 30%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-True-args2] PASSED                                                                                                 [ 34%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-True-args3] PASSED                                                                                                 [ 38%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-True-args4] PASSED                                                                                                 [ 42%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-True-args5] PASSED                                                                                                 [ 46%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-True-args6] PASSED                                                                                                 [ 50%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-False-args7] PASSED                                                                                                [ 53%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-False-args8] PASSED                                                                                                [ 57%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-False-args9] PASSED                                                                                                [ 61%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-False-args10] PASSED                                                                                               [ 65%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-True-args11] PASSED                                                                                                [ 69%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_install_arg_matrix[volttron_instance0-True-args12] PASSED                                                                                                [ 73%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_agent_filters[volttron_instance0] PASSED                                                                                                                 [ 76%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_vctl_start_stop_restart_by_uuid_should_succeed[volttron_instance0] PASSED                                                                                [ 80%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_vctl_start_stop_restart_by_tag_should_succeed[volttron_instance0] PASSED                                                                                 [ 84%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_vctl_start_stop_restart_by_all_tagged_should_succeed[volttron_instance0] PASSED                                                                          [ 88%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_vctl_start_stop_restart_should_raise_error_on_invalid_options[volttron_instance0-start] PASSED                                                           [ 92%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_vctl_start_stop_restart_should_raise_error_on_invalid_options[volttron_instance0-stop] PASSED                                                            [ 96%]
volttrontesting/platform/control_tests/test_vctl_commands.py::test_vctl_start_stop_restart_should_raise_error_on_invalid_options[volttron_instance0-restart] PASSED                                                         [100%]


== 26 passed, 2 warnings in 188.26s (0:03:08) ==


```

Associated Workflow also passes:

https://github.com/VOLTTRON/volttron/actions/runs/1895768008

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by craig8** [comment]
@bonicim what issue is this against
please add it so we can re-look at the design of this parameter.

**Comment by bonicim** [comment]
> @bonicim what issue is this against please add it so we can re-look at the design of this parameter.

This issue is logged in the internal JIRA board. I created issue #2881 on Github to track this publicly. I will update #2881 with a link to the Jira ticket.

**Comment by bonicim** [comment]
Added tests for the following vctl commands:

* vctl start (some_uuid)
* vctl stop (some_uuid)
* vctl restart (some_uuid)

* vctl start --tag (some_tag)
* vctl stop --tag (some_tag)
* vctl restart --tag (some_tag)

* vctl start --all-tagged 
* vctl stop --all-tagged 
* vctl restart --all-tagged 

Also updated the assertion workflow for `test_needs_connection_with_connection`, `test_no_connection`, and `test_needs_connection` so that they don't fail in CI Workflows. See failed workflows in https://github.com/VOLTTRON/volttron/actions/workflows/pytest-vctl.yml. 

Successful workflow at https://github.com/VOLTTRON/volttron/actions/runs/1895768008

**Comment by craig8** [comment]
vctl start --all does not produce an error.

I would expect it to do the same thing as

vctl start foo when foo does not exist

start: error: agent not found: foo

This may be an issue for a different item however.

**Comment by craig8** [comment]
Before this pull request the following would happen when passing --all

````
(volttron) gridappsd@gridappsd_dev_2004:/repos/volttron$ vctl start --all
usage: vctl command [OPTIONS] ... start [-h] [--name] [--tag] [--uuid] [-c FILE] [--debug] [-t SECS]
                                        [--msgdebug MSGDEBUG] [--vip-address ZMQADDR]
                                        pattern [pattern ...]
vctl command [OPTIONS] ... start: error: the following arguments are required: pattern
````

Because we are changing this, I think that either --foo or --anything should still raise an error if it's not one of the predefined ones that we have when viewing ````vctl start --help````

**Review by craig8 — CHANGES_REQUESTED** [review]
See above comments about command line interface.

**Comment by bonicim** [comment]
> Before this pull request the following would happen when passing --all
> 
> ```
> (volttron) gridappsd@gridappsd_dev_2004:/repos/volttron$ vctl start --all
> usage: vctl command [OPTIONS] ... start [-h] [--name] [--tag] [--uuid] [-c FILE] [--debug] [-t SECS]
>                                         [--msgdebug MSGDEBUG] [--vip-address ZMQADDR]
>                                         pattern [pattern ...]
> vctl command [OPTIONS] ... start: error: the following arguments are required: pattern
> ```
> 
> Because we are changing this, I think that either --foo or --anything should still raise an error if it's not one of the predefined ones that we have when viewing `vctl start --help`

Good catch. Makes sense. I'll update the code to reflect that behavior and also add a test for this as well.

**Comment by bonicim** [comment]
Commit 6e10 disables "allow_abbrev" on the argparser. By default, "allow_abbrev" is set to true, which allows for abbreviations on long options. For example, the long option "--all-tagged" was shortened to "--all", thus allowing the command "vctl start --all" to be a legal command. For details, see https://docs.python.org/3.9/library/argparse.html#prefix-matching

**Pull request merged**
