### PR TITLE
Feature/driven remote actuator

### PR DESCRIPTION
**Pull request by rlutes**
Updates for driven for use with MATLAB and Airside/Economizer driven agents.  Cleaned up analysis result publishing and address bug with actuation on subdevices.

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/546)

### CODE REVIEW

**Comment by craig8** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[applications/pnnl/AirsideRCxAgent/airside/drivenagent.py, line 197 \[r3\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI-y3lZTiQBsVQmhWVu:-KI-y3lZTiQBsVQmhWVv:-1502323893) ([raw file](https://github.com/volttron/volttron/blob/d9e532f2b021868ccf85e5d830aed340246bf3b6/applications/pnnl/AirsideRCxAgent/airside/drivenagent.py#L197)):*
> ```Python
>             agent = Agent(address=vip_destination)
>             gevent.spawn(agent.core.run, event)
>             event.wait(timeout=10)
> ```

Do you think 10 seconds is enough for the actuator to respond from the remote platform?

---

*[applications/pnnl/AirsideRCxAgent/airside/drivenagent.py, line 412 \[r3\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI-ydgXkWmsbOgwnrIa:-KI-ydgXkWmsbOgwnrIb:572532604) ([raw file](https://github.com/volttron/volttron/blob/d9e532f2b021868ccf85e5d830aed340246bf3b6/applications/pnnl/AirsideRCxAgent/airside/drivenagent.py#L412)):*
> ```Python
>             Calls the actuator's request_new_schedule method to get
>                     device schedule
> ```

Can you document what command_equip holds?

---

*[applications/pnnl/AirsideRCxAgent/airside/drivenagent.py, line 428 \[r3\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI-ylI_7bgBudKp7P8D:-KI-ylI_7bgBudKp7P8E:244278454) ([raw file](https://github.com/volttron/volttron/blob/d9e532f2b021868ccf85e5d830aed340246bf3b6/applications/pnnl/AirsideRCxAgent/airside/drivenagent.py#L428)):*
> ```Python
>             _now = dt.now()
>             str_now = _now.strftime(DATE_FORMAT)
>             _end = _now + td(minutes=1.5)
> ```

Should these be the td minutes be configurable either on the fly or from the configuration file of the agent?

---

*[applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py, line 198 \[r3\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI-zBoSLq4DdUc3NYL_:-KI-zBoSLq4DdUc3NYLa:2114112871) ([raw file](https://github.com/volttron/volttron/blob/d9e532f2b021868ccf85e5d830aed340246bf3b6/applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py#L198)):*
> ```Python
>             gevent.spawn(agent.core.run, event)
>             event.wait(timeout=10)
>             return agent
> ```

Is this remote timeout enough?

---

*[applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py, line 297 \[r3\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI-zNEL7rXqxp41QeUE:-KI-zNEL7rXqxp41QeUF:-866084331) ([raw file](https://github.com/volttron/volttron/blob/d9e532f2b021868ccf85e5d830aed340246bf3b6/applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py#L297)):*
> ```Python
>             :returns: Same as results param.
>             :rtype: Results object \\volttron.platform.agent.driven"""
>             _log.debug('Processing Results!')
> ```

I think processing results should be at an info level rather than debug.

---

*[applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py, line 411 \[r3\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI-zYCv8O5MnlwYfaYK:-KI-zYCv8O5MnlwYfaYL:1629384286) ([raw file](https://github.com/volttron/volttron/blob/d9e532f2b021868ccf85e5d830aed340246bf3b6/applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py#L411)):*
> ```Python
>             """
>             Calls the actuator's request_new_schedule method to get
>                     device schedule
> ```

Why are these lines repeated?

---

*[applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py, line 416 \[r3\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI-zhz7AaSUJ_jBq1Y2:-KI-zhz7AaSUJ_jBq1Y3:804420906) ([raw file](https://github.com/volttron/volttron/blob/27f079522c66b962496abf0f67b7ce87656ab62a/applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py#L416)):*
> ```Python
>                 schedule_request = [[actuation_device, str_now, str_end]]
>                 try:
>                     result = self.vip.rpc.call('platform.actuator',
> ```

Do you really want this in info instead of debug?

---

*[applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py, line 438 \[r3\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI-zoVEOSqXs99tRGUf:-KI-zoVEOSqXs99tRGUg:1376779627) ([raw file](https://github.com/volttron/volttron/blob/d9e532f2b021868ccf85e5d830aed340246bf3b6/applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py#L438)):*
> ```Python
>                                                      'request_new_schedule',
>                                                      actuator_id, actuation_device, 'HIGH',
>                                                      schedule_request).get(timeout=4)
> ```

timeout enough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/546)*

**Comment by rlutes** [comment]
Addressed comments.

**Comment by craig8** [comment]
@rlutes I didn't mean that you needed to put everything to info.  The paradigm I was looking for would be info on just the beginning of the processing results and then debug for the loops that give you full info.  That's what I was meaning.  Of course that means the logging needs to be fixed to actually do that, but I digress.

If you want me to go with the info I am fine with it however.  Just please let me know here or via email.

**Comment by craig8** [comment]
Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[applications/pnnl/AirsideRCxAgent/airside/drivenagent.py, line 413 \[r4\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI0HcytBIHjIAk41cT7:-KI0HcytBIHjIAk41cT8:-108173898) ([raw file](https://github.com/volttron/volttron/blob/ab9e5df1481710136090b18d7b843247826b43b6/applications/pnnl/AirsideRCxAgent/airside/drivenagent.py#L413)):*
> ```Python
>             Calls the actuator's request_new_schedule method to get
>                     device schedule
>             :param command_equip: contains the names are of the devices
> ```

grammar notice

---

*[applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py, line 413 \[r4\]](https://reviewable.io:443/reviews/volttron/volttron/546#-KI0Hr6ah_Pgg307OYyM:-KI0Hr6c4wM9cRz8z0ba:-1865903358) ([raw file](https://github.com/volttron/volttron/blob/ab9e5df1481710136090b18d7b843247826b43b6/applications/pnnl/DrivenMatlabAgent/drivenmatlab/drivenagent.py#L413)):*
> ```Python
>             Calls the actuator's request_new_schedule method to get
>                     device schedule
>             :param command_equip: contains the names are of the devices
> ```

grammar

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/546)*

**Comment by craig8** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/volttron/volttron/546)*

**Pull request merged**
