### PR TITLE
Port to Python 3.

### PR DESCRIPTION
**Pull request by ocschwar**
Updated the print statements,
exception handlers, and changed the dependency
from smap2-... to smap. The latter is not yet available from
Pypi, so you need  to obtain it from
https://code.google.com/archive/p/smap-data/

Or the github repo which is at

https://github.com/SoftwareDefinedBuildings/smap/tree/master/python/smap/iface/modbus

---
This change is [Reviewable](https://reviewable.io/reviews/volttron/volttron/640)

### CODE REVIEW

**Comment by craig8** [comment]
@ocschwar Thank you very much for your commitment for getting our project to python 3.  Some things that you might want to know about before you continue however.

1. Our develop branch is our working branch.  You are submitting this pull request against master and therefore are bypassing the majority of our changes.
1. In the develop branch there are a LOT of integration tests wrapped around the core agent code.  Please feel free to work with those as they "prove" that the code will work the same in both 2.7+ and 3 environments.
1. Rather than dumping 2.7 we are looking to support both 2.7 and 3 within the same codebase.  Please remember that as you are modifying code.

@jhaack @kmonson

**Comment by jhaack** [comment]
Supporting 2.7 and 3 is definitely a goal. We need to make sure all our underlying libraries (especially BACPypes and PyModbus) are compatible with 3.

Thanks for taking a crack at this.

**Comment by kmonson** [comment]
While I have not tried either one both libraries claim to support 3.

**Comment by craig8** [comment]
@ocschwar are you still willing to work on this?

**Comment by ocschwar** [comment]
HI, yes, I am, though for the moment I am committed to getting a Volttron server up and running for my particular project (which has a long enough horizon that I had to look at a Python 3 migration as a first step.)

**Comment by ocschwar** [comment]
Shall I close this?

**Comment by craig8** [comment]
You should definately be working off of the develop branch then!  As things have changed dramatically since the release of the master branch.

Also note that there are documents at http://volttron.readthedocs.org and on stackoverflow http://stackoverflow.com/tags/volttron

Please keep me up to date as you go forward and hopefully we won't make the conversion to 3 any harder than it is :)

**Comment by craig8** [comment]
Closing until @ocschwar is ready to go.

**Pull request closed without merging**
